-- Module: finance — canonical schema
-- Description: All money primitives in one module/DB for atomicity — payment
--              sessions + append-only transaction ledger (external rail money
--              flow), wallets keyed by account+currency (available/held
--              balances) + wallet ledger, and registered bank accounts. order and account
--              reference these by id only (no cross-schema FK).
--
-- Two ledgers, one boundary: "transaction" records legs on **external rails**
-- (card, VNPay, …) under a session; money that only moves inside a wallet is
-- recorded solely in "wallet_transaction". Never write the same movement to both.
--
-- Cashing out is a session of kind 'withdrawal' (not its own table): the
-- destination bank account id and the admin resolution live in "data", and the
-- wallet debit lands in "wallet_transaction" with kind 'withdrawal'.

-- Enums

-- What a session is for. An enum, not free text: "kind" routes the money, so a typo
-- would be a session no handler ever picks up.
CREATE TYPE "session_kind" AS ENUM ('buyer-checkout', 'seller-confirmation-fee', 'seller-payout', 'withdrawal');
-- Payment session lifecycle
CREATE TYPE "session_status" AS ENUM ('pending', 'processing', 'success', 'cancelled', 'failed');
-- Ledger leg lifecycle: pending -> success or failed, and success is terminal.
-- Deliberately narrower than "session_status", so a state a leg can never reach is not
-- representable in the column.
CREATE TYPE "transaction_status" AS ENUM ('pending', 'success', 'failed');
-- Tax code / KYC verification lifecycle.
CREATE TYPE "verification_status" AS ENUM ('pending', 'verified', 'rejected');
-- Wallet ledger movement kind
CREATE TYPE "wallet_txn_kind" AS ENUM ('topup', 'escrow-hold', 'escrow-release', 'payout', 'refund', 'withdrawal', 'fee', 'adjustment');

-- Tables

-- The two ledgers are the trail for money itself; this is the trail for everything
-- else — a bank account added or removed, a tax code verified, a wallet adjusted by an
-- admin.
CREATE TABLE IF NOT EXISTS "audit_log" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY,
    "version" BIGINT NOT NULL DEFAULT 1, -- Incremented on each change to the same record
    "table_name" VARCHAR(100) NOT NULL,
    "record_id" BIGINT NOT NULL,
    "change_type" VARCHAR(10) NOT NULL, -- 'insert', 'update', 'delete'
    "code" VARCHAR(100) NOT NULL, -- e.g. Business code 'bank_account.remove', 'tax_info.verify'
    "changed_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "changed_by" BIGINT, -- account_id of the user who made the change (if applicable)
    "diff" JSONB NOT NULL, -- JSON diff of the record's fields (for insert only, other diff = snapshot)
    "snapshot" JSONB NOT NULL, -- Full record values after the change
    CONSTRAINT "audit_log_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "audit_log_table_name_record_id_version_key" UNIQUE ("table_name", "record_id", "version")
);

-- Payment intent: one logical money flow (checkout, fee, payout, withdrawal).
-- Mutable status; has 0..N transaction rows below for split-tender support.
CREATE TABLE IF NOT EXISTS "payment_session" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY, -- BY DEFAULT: the app pre-allocates it with
    -- nextval(pg_get_serial_sequence('payment_session', 'id')) and inserts it
    -- explicitly, so a provider can be handed the id before the row exists.
    "kind" "session_kind" NOT NULL,
    "status" "session_status" NOT NULL,
    "from_id" BIGINT, -- Account initiating (buyer, seller, NULL = system)
    "to_id" BIGINT, -- Counterparty (buyer, seller, NULL = system)
    "note" TEXT NOT NULL,

    "currency" VARCHAR(3) NOT NULL, -- Buyer-facing currency; every child transaction settles via this currency
    "total_amount" BIGINT NOT NULL, -- Expected total in buyer-facing currency

    -- FX snapshot frozen at session creation. NULL when no cross-currency
    -- conversion was needed (every item already priced in `currency`).
    -- Shape: { "base": "USD", "rates": { "VND": "24500.0", ... }, "fetched_at": "..." }
    "fx_snapshot" JSONB,

    -- Kind-specific context: cost breakdown, line items snapshot, gateway URLs per
    -- rail, provider metadata; for 'withdrawal' also the destination bank_account id
    -- and the admin resolution.
    "data" JSONB NOT NULL,

    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "paid_at" TIMESTAMPTZ, -- Set when session reaches success
    "expired_at" TIMESTAMPTZ NOT NULL, -- pending sessions auto-void after this timestamp

    CONSTRAINT "payment_session_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "payment_session_currency_format" CHECK ("currency" ~ '^[A-Z]{3}$'),
    CONSTRAINT "payment_session_total_amount_positive" CHECK ("total_amount" > 0)
);
CREATE INDEX IF NOT EXISTS "payment_session_kind_idx" ON "payment_session" ("kind");
CREATE INDEX IF NOT EXISTS "payment_session_from_id_idx" ON "payment_session" ("from_id");
-- "Money I received": seller payouts and refunds land on this side.
CREATE INDEX IF NOT EXISTS "payment_session_to_id_idx" ON "payment_session" ("to_id");
-- The auto-void job: unfinished sessions past their deadline, oldest first. Ordered on
-- "expired_at" rather than "status", which has too few values to lead an index.
CREATE INDEX IF NOT EXISTS "payment_session_expiring_idx"
    ON "payment_session" ("expired_at")
    WHERE "status" IN ('pending', 'processing');
-- The admin withdrawal queue: cash-outs waiting on a human, oldest first. Real money
-- leaves the platform through these, so the queue is worked in order and has to stay
-- cheap however long the history behind it gets. Neither "kind" nor "status" can lead
-- this on its own: each has a handful of values, and the pair still has to deliver the
-- ordering.
CREATE INDEX IF NOT EXISTS "payment_session_withdrawal_queue_idx"
    ON "payment_session" ("created_at")
    WHERE "kind" = 'withdrawal' AND "status" IN ('pending', 'processing');

-- Append-only ledger leg: one row per **external rail** movement (card charge,
-- refund leg). Status transitions pending -> success/failed only; success is
-- terminal. Reversals are NEW rows with negative amount + reverses_id pointing
-- to the original. Wallet-only movements belong in "wallet_transaction".
CREATE TABLE IF NOT EXISTS "transaction" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY, -- pre-allocated like "payment_session"."id"
    "session_id" BIGINT NOT NULL,
    "status" "transaction_status" NOT NULL,
    "note" TEXT NOT NULL,
    "error" TEXT,

    -- Concrete rail used; every leg has one, since wallet-only movements are not
    -- recorded here.
    "payment_option" VARCHAR(100) NOT NULL, -- References common.option (payment); same kebab-case slug

    -- The gateway's own id for this leg. Providers deliver webhooks at least once and
    -- retry until they get a 200, so this is what stops a redelivery from being booked
    -- as a second charge. NULL only while the leg is still pending and the gateway has
    -- not assigned one yet.
    "provider_ref" TEXT,

    -- Rail-specific payload: gateway request/response, webhook payload, processor IDs
    "data" JSONB NOT NULL,

    -- Signed: positive = original charge; negative = reversal (refund leg).
    -- Per-rail currency because split-tender may mix currencies (e.g. wallet VND + card USD).
    -- Conversion rates live on payment_session.fx_snapshot, not per-tx.
    "amount" BIGINT NOT NULL,
    "currency" VARCHAR(3) NOT NULL, -- Currency the rail actually debits / credits

    -- Self-FK to the original charge this row reverses; NULL on originals.
    "reverses_id" BIGINT,

    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "settled_at" TIMESTAMPTZ, -- Set when status reaches success
    "expired_at" TIMESTAMPTZ, -- Gateway URL expiry; NULL when the rail has none

    CONSTRAINT "transaction_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "transaction_sign_matches_reverses_chk" CHECK (("amount" > 0 AND "reverses_id" IS NULL) OR ("amount" < 0 AND "reverses_id" IS NOT NULL)),
    CONSTRAINT "transaction_no_self_reverse_chk" CHECK ("reverses_id" IS NULL OR "reverses_id" != "id"),
    CONSTRAINT "transaction_currency_format" CHECK ("currency" ~ '^[A-Z]{3}$'),
    CONSTRAINT "transaction_payment_option_format" CHECK ("payment_option" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),

    CONSTRAINT "transaction_session_id_fkey" FOREIGN KEY ("session_id")
        REFERENCES "payment_session" ("id") ON DELETE NO ACTION,
    CONSTRAINT "transaction_reverses_id_fkey" FOREIGN KEY ("reverses_id")
        REFERENCES "transaction" ("id") ON DELETE NO ACTION
);
CREATE INDEX IF NOT EXISTS "transaction_session_id_idx" ON "transaction" ("session_id");
-- The idempotency guard: at most one leg per gateway reference, so a redelivered
-- webhook violates this instead of booking a second charge.
CREATE UNIQUE INDEX IF NOT EXISTS "transaction_provider_ref_unique"
    ON "transaction" ("payment_option", "provider_ref")
    WHERE "provider_ref" IS NOT NULL;
-- One reversal per original leg. Two invariants cannot be expressed here because they
-- span rows, and the service has to hold them: a reversal may not exceed the original
-- in magnitude, and it must be in the original's currency.
CREATE UNIQUE INDEX IF NOT EXISTS "transaction_reverses_id_unique" ON "transaction" ("reverses_id") WHERE "reverses_id" IS NOT NULL;
-- Settled legs only: revenue / refund totals scan this partial index instead of
-- going through a view (the predicate stays in the repo's SQL).
CREATE INDEX IF NOT EXISTS "transaction_settled_idx" ON "transaction" ("created_at" DESC) WHERE "status" = 'success';

-- Wallet balances (available vs escrow-held), one row per account *and currency*.
-- account_id is a cross-module ref to account.account (no FK).
-- Every balance change takes SELECT ... FOR UPDATE on this row: it serializes the
-- movement and is where "wallet_transaction"."seq" is allocated.
CREATE TABLE IF NOT EXISTS "wallet" (
    "account_id" BIGINT NOT NULL,
    -- ISO 4217, not derived from the account's country: one currency spans many
    -- countries, and a VN seller may still want a USD balance.
    "currency" VARCHAR(3) NOT NULL,
    "available_balance" BIGINT NOT NULL DEFAULT 0, -- spendable / withdrawable
    "held_balance" BIGINT NOT NULL DEFAULT 0, -- locked in escrow
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Currency is in the key so a second balance is an INSERT, not a migration of
    -- live money. Balances never mix: converting is two movements plus an fx rate.
    CONSTRAINT "wallet_pkey" PRIMARY KEY ("account_id", "currency"),
    CONSTRAINT "wallet_currency_format" CHECK ("currency" ~ '^[A-Z]{3}$'),
    CONSTRAINT "wallet_available_balance_non_negative" CHECK ("available_balance" >= 0),
    CONSTRAINT "wallet_held_balance_non_negative" CHECK ("held_balance" >= 0)
);

-- Append-only wallet ledger: every balance change with before/after snapshot,
-- and the only place wallet-internal movements are recorded (NFR-009, BR-013).
-- "seq" gives each wallet a total order that "created_at" cannot (timestamps tie).
-- Allocate it under the same SELECT ... FOR UPDATE on "wallet" as the balance change.
CREATE TABLE IF NOT EXISTS "wallet_transaction" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY,
    "account_id" BIGINT NOT NULL, -- cross-ref account.account; no FK
    -- Which wallet this moves. Stored rather than inferred: a row must state its own
    -- amount's unit, and topup/adjustment carry no session to look an fx rate up from.
    "currency" VARCHAR(3) NOT NULL,
    "seq" BIGINT NOT NULL, -- per-wallet position in the ledger, starting at 1
    "kind" "wallet_txn_kind" NOT NULL,
    "available_delta" BIGINT NOT NULL DEFAULT 0, -- signed change to available balance
    "held_delta" BIGINT NOT NULL DEFAULT 0, -- signed change to held balance
    "available_after" BIGINT NOT NULL, -- available balance after this movement
    "held_after" BIGINT NOT NULL, -- held balance after this movement
    -- Legs of one logical movement share a group: a checkout is buyer debit + escrow
    -- hold + fee, and without this the "does the money add up" query cannot be written.
    "group_id" BIGINT,
    "ref_type" TEXT, -- cross-module ref kind ('order', 'payment-session'); NULL for adjustments
    "ref_id" BIGINT, -- id of the referenced entity, kinded by "ref_type"
    -- Caller-supplied idempotency key, e.g. 'order:412:escrow-hold'. Retrying a
    -- movement reuses the key and hits the unique index instead of double-posting.
    "idempotency_key" TEXT,
    "note" TEXT NOT NULL DEFAULT '',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "wallet_transaction_pkey" PRIMARY KEY ("id"),
    -- One ledger per wallet, so the sequence restarts per currency.
    CONSTRAINT "wallet_transaction_wallet_seq_key" UNIQUE ("account_id", "currency", "seq"),
    CONSTRAINT "wallet_transaction_currency_format" CHECK ("currency" ~ '^[A-Z]{3}$'),
    -- The same non-negative rule "wallet" enforces on the balance. Without it the
    -- ledger can record a balance the wallet table would have rejected, and the two
    -- disagree about what happened.
    CONSTRAINT "wallet_transaction_after_non_negative" CHECK (
        "available_after" >= 0 AND "held_after" >= 0
    ),
    -- A row that moves nothing is noise in a ledger.
    CONSTRAINT "wallet_transaction_moves_something" CHECK (
        "available_delta" <> 0 OR "held_delta" <> 0
    ),
    -- Same schema, so this one is a real FK: a ledger row for a wallet that was never
    -- opened is money recorded against nothing.
    CONSTRAINT "wallet_transaction_wallet_fkey" FOREIGN KEY ("account_id", "currency")
        REFERENCES "wallet" ("account_id", "currency")
);
-- No separate ("account_id","currency","seq" DESC) index: "wallet_transaction_wallet_seq_key"
-- already orders those columns and a btree scans backwards just as cheaply.
CREATE INDEX IF NOT EXISTS "wallet_transaction_ref_idx" ON "wallet_transaction" ("ref_type", "ref_id");
CREATE UNIQUE INDEX IF NOT EXISTS "wallet_transaction_idempotency_key_unique"
    ON "wallet_transaction" ("idempotency_key")
    WHERE "idempotency_key" IS NOT NULL;
-- Reconciliation: pull every leg of one movement.
CREATE INDEX IF NOT EXISTS "wallet_transaction_group_id_idx"
    ON "wallet_transaction" ("group_id")
    WHERE "group_id" IS NOT NULL;

-- Registered bank account: a saved payout / withdrawal destination, referenced
-- by id from a 'withdrawal' session's data.
-- account_id is a cross-module ref to account.account (no FK).
CREATE TABLE IF NOT EXISTS "bank_account" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY,
    "account_id" BIGINT NOT NULL,
    "bank_code" VARCHAR(20) NOT NULL, -- bank identifier (e.g. 'vcb', 'tcb')
    "account_number" VARCHAR(50) NOT NULL,
    "account_holder" VARCHAR(100) NOT NULL,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Soft delete: a completed withdrawal names this row from its session "data", and
    -- that is the record of where real money went. Financial history cannot lose its
    -- payee.
    "deleted_at" TIMESTAMPTZ,

    CONSTRAINT "bank_account_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "bank_account_account_id_idx" ON "bank_account" ("account_id");
CREATE UNIQUE INDEX IF NOT EXISTS "bank_account_one_default_per_account"
    ON "bank_account" ("account_id")
    WHERE "is_default" AND "deleted_at" IS NULL;
-- One bank account registered under several platform accounts is a mule signal; this
-- makes the check a lookup rather than a scan.
CREATE INDEX IF NOT EXISTS "bank_account_bank_code_account_number_idx"
    ON "bank_account" ("bank_code", "account_number");

CREATE TABLE IF NOT EXISTS "tax_info" (
    "account_id"          BIGINT       NOT NULL, -- cross-ref account.account
    "tax_code"            VARCHAR(14)  NOT NULL, -- Vietnamese MST: 10 digits, or 10-3 for a branch
    "tax_code_type"       VARCHAR(20)  NOT NULL, -- 'individual' | 'business' | 'household'
    "legal_name"          TEXT         NOT NULL,
    "verification_status" "verification_status" NOT NULL DEFAULT 'pending',
    "verified_at"         TIMESTAMPTZ,
    "verification_source" TEXT,

    "created_at"          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "tax_info_pkey" PRIMARY KEY ("account_id"),
    CONSTRAINT "tax_info_tax_code_format" CHECK ("tax_code" ~ '^\d{10}(-\d{3})?$')
);

-- Only one verified tax code may exist across all accounts.
CREATE UNIQUE INDEX IF NOT EXISTS "tax_info_tax_code_verified_uq"
    ON "tax_info" ("tax_code")
    WHERE "verification_status" = 'verified';
