// Code generated by pgtempl; DO NOT EDIT.
package accountdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5"

	"shopnexus-server/internal/shared/paginate"
	"shopnexus-server/internal/shared/repolist"
)

// ListFavoriteParams filters "account"."favorite". A slice field is an IN/ANY match: nil = skip,
// non-nil empty = match nothing. *From/*To pairs are inclusive range bounds.
type ListFavoriteParams struct {
	paginate.Params

	Id              []int64
	AccountId       []uuid.UUID
	SpuId           []uuid.UUID
	DateCreated     []time.Time
	DateCreatedFrom null.Time
	DateCreatedTo   null.Time
}

func favoriteListConds(f ListFavoriteParams, conds *[]string, args pgx.NamedArgs) {
	if f.Id != nil {
		*conds = append(*conds, `"id" = ANY(@id)`)
		args["id"] = f.Id
	}
	if f.AccountId != nil {
		*conds = append(*conds, `"account_id" = ANY(@account_id)`)
		args["account_id"] = f.AccountId
	}
	if f.SpuId != nil {
		*conds = append(*conds, `"spu_id" = ANY(@spu_id)`)
		args["spu_id"] = f.SpuId
	}
	if f.DateCreated != nil {
		*conds = append(*conds, `"date_created" = ANY(@date_created)`)
		args["date_created"] = f.DateCreated
	}
	if f.DateCreatedFrom.Valid {
		*conds = append(*conds, `"date_created" >= @date_created_from`)
		args["date_created_from"] = f.DateCreatedFrom.Time
	}
	if f.DateCreatedTo.Valid {
		*conds = append(*conds, `"date_created" <= @date_created_to`)
		args["date_created_to"] = f.DateCreatedTo.Time
	}
}

func favoriteListSpec(f ListFavoriteParams) repolist.Spec[AccountFavorite] {
	return repolist.Spec[AccountFavorite]{
		Table: `"account"."favorite"`,
		PK:    "id",
		Whitelist: paginate.Whitelist{
			"id":           {Col: `"id"`, Cast: "int8"},
			"date_created": {Col: `"date_created"`, Cast: "timestamptz"},
		},
		BindConds: func(conds *[]string, args pgx.NamedArgs) { favoriteListConds(f, conds, args) },
	}
}

// ListFavorite runs offset (?page) or cursor (?cursor/?sort) pagination over "account"."favorite".
func (q *Queries) ListFavorite(ctx context.Context, f ListFavoriteParams) (paginate.PaginateResult[AccountFavorite], error) {
	return repolist.List(ctx, q.db, favoriteListSpec(f), f.Params)
}
