// Code generated by genrestate; DO NOT EDIT.

package analyticbiz

import (
	"context"
	"encoding/json"
	"github.com/google/uuid"
	restate "github.com/restatedev/sdk-go"
	analyticdb "shopnexus-server/internal/module/analytic/db/sqlc"
	analyticmodel "shopnexus-server/internal/module/analytic/model"
	"shopnexus-server/internal/shared/besteffort"
	"shopnexus-server/internal/shared/paginate"
	restatec "shopnexus-server/internal/shared/restate"
)

const serviceName = "Analytic"

// AnalyticBizCall mirrors the command methods of AnalyticBiz as request-response calls.
type AnalyticBizCall interface {
	CreateInteraction(ctx context.Context, params CreateInteractionParams) error
	HandlePopularityEvent(ctx context.Context, event analyticmodel.Interaction) error
}

// AnalyticBizSender mirrors the command methods of AnalyticBiz as one-way (fire-and-forget) calls.
type AnalyticBizSender interface {
	CreateInteraction(ctx context.Context, params CreateInteractionParams) error
	HandlePopularityEvent(ctx context.Context, event analyticmodel.Interaction) error
}

// AnalyticBizFuture mirrors the command methods of AnalyticBiz returning response futures for
// racing or parallel calls. Only usable inside a Restate handler context.
type AnalyticBizFuture interface {
	CreateInteraction(rctx restate.Context, params CreateInteractionParams) restate.ResponseFuture[restate.Void]
	HandlePopularityEvent(rctx restate.Context, event analyticmodel.Interaction) restate.ResponseFuture[restate.Void]
}

// AnalyticBizClient is the cross-module client: query methods are flat (non-durable),
// Call()/Future()/Send() reach the durable command surfaces.
type AnalyticBizClient interface {
	GetProductPopularity(ctx context.Context, spuID uuid.UUID) (analyticdb.AnalyticProductPopularity, error)
	ListTopProductPopularity(ctx context.Context, params paginate.Params) ([]analyticdb.AnalyticProductPopularity, error)
	Call() AnalyticBizCall
	Future() AnalyticBizFuture
	Send() AnalyticBizSender
}

// AnalyticRestateCall implements AnalyticBizCall via Restate HTTP ingress.
type AnalyticRestateCall struct {
	call *restatec.CallClient
}

var _ AnalyticBizCall = (*AnalyticRestateCall)(nil)

func NewAnalyticRestateCall(restateIngressURL string) *AnalyticRestateCall {
	return &AnalyticRestateCall{call: restatec.NewCallClient(restateIngressURL)}
}

func (p *AnalyticRestateCall) CreateInteraction(ctx context.Context, params CreateInteractionParams) error {
	return restatec.CallVoid(ctx, p.call, serviceName, "CreateInteraction", params)
}

func (p *AnalyticRestateCall) HandlePopularityEvent(ctx context.Context, event analyticmodel.Interaction) error {
	return restatec.CallVoid(ctx, p.call, serviceName, "HandlePopularityEvent", event)
}

// AnalyticRestateSender implements AnalyticBizSender.
type AnalyticRestateSender struct {
	client *restatec.SendClient
}

var _ AnalyticBizSender = (*AnalyticRestateSender)(nil)

func (s *AnalyticRestateSender) CreateInteraction(ctx context.Context, params CreateInteractionParams) error {
	return restatec.Send(ctx, s.client, serviceName, "CreateInteraction", params)
}

func (s *AnalyticRestateSender) HandlePopularityEvent(ctx context.Context, event analyticmodel.Interaction) error {
	return restatec.Send(ctx, s.client, serviceName, "HandlePopularityEvent", event)
}

// AnalyticRestateFuture implements AnalyticBizFuture via the Restate SDK.
type AnalyticRestateFuture struct{}

var _ AnalyticBizFuture = (*AnalyticRestateFuture)(nil)

func (f *AnalyticRestateFuture) CreateInteraction(rctx restate.Context, params CreateInteractionParams) restate.ResponseFuture[restate.Void] {
	return restate.Service[restate.Void](rctx, serviceName, "CreateInteraction").RequestFuture(params)
}

func (f *AnalyticRestateFuture) HandlePopularityEvent(rctx restate.Context, event analyticmodel.Interaction) restate.ResponseFuture[restate.Void] {
	return restate.Service[restate.Void](rctx, serviceName, "HandlePopularityEvent").RequestFuture(event)
}

// AnalyticService adapts AnalyticBiz into restate.Context handlers for restate.Reflect.
type AnalyticService struct {
	biz AnalyticBiz
}

func NewAnalyticService(biz AnalyticBiz) *AnalyticService { return &AnalyticService{biz: biz} }

func (s *AnalyticService) ServiceName() string { return serviceName }

func (s *AnalyticService) CreateInteraction(ctx restate.Context, params CreateInteractionParams) error {
	return s.biz.CreateInteraction(ctx, params)
}

func (s *AnalyticService) HandlePopularityEvent(ctx restate.Context, event analyticmodel.Interaction) error {
	return s.biz.HandlePopularityEvent(ctx, event)
}

func (s *AnalyticService) GetProductPopularity(ctx restate.Context, spuID uuid.UUID) (analyticdb.AnalyticProductPopularity, error) {
	return s.biz.GetProductPopularity(ctx, spuID)
}

func (s *AnalyticService) ListTopProductPopularity(ctx restate.Context, params paginate.Params) ([]analyticdb.AnalyticProductPopularity, error) {
	return s.biz.ListTopProductPopularity(ctx, params)
}

// AnalyticBizFlat is the flat (non-durable query) surface of AnalyticBiz.
type AnalyticBizFlat interface {
	GetProductPopularity(ctx context.Context, spuID uuid.UUID) (analyticdb.AnalyticProductPopularity, error)
	ListTopProductPopularity(ctx context.Context, params paginate.Params) ([]analyticdb.AnalyticProductPopularity, error)
}

// analyticBizBestEffortLocal delegates flat queries to the in-process biz.
type analyticBizBestEffortLocal struct{ biz AnalyticBiz }

var _ AnalyticBizFlat = (*analyticBizBestEffortLocal)(nil)

func (b *analyticBizBestEffortLocal) GetProductPopularity(ctx context.Context, spuID uuid.UUID) (analyticdb.AnalyticProductPopularity, error) {
	return b.biz.GetProductPopularity(ctx, spuID)
}

func (b *analyticBizBestEffortLocal) ListTopProductPopularity(ctx context.Context, params paginate.Params) ([]analyticdb.AnalyticProductPopularity, error) {
	return b.biz.ListTopProductPopularity(ctx, params)
}

// analyticBizBestEffortRemote routes flat queries over HTTP/2.
type analyticBizBestEffortRemote struct{ call *besteffort.CallClient }

var _ AnalyticBizFlat = (*analyticBizBestEffortRemote)(nil)

func (b *analyticBizBestEffortRemote) GetProductPopularity(ctx context.Context, spuID uuid.UUID) (analyticdb.AnalyticProductPopularity, error) {
	return besteffort.Call[analyticdb.AnalyticProductPopularity](ctx, b.call, serviceName, "GetProductPopularity", spuID)
}

func (b *analyticBizBestEffortRemote) ListTopProductPopularity(ctx context.Context, params paginate.Params) ([]analyticdb.AnalyticProductPopularity, error) {
	return besteffort.Call[[]analyticdb.AnalyticProductPopularity](ctx, b.call, serviceName, "ListTopProductPopularity", params)
}

// analyticBizClient holds the flat query impl and the durable command proxies.
type analyticBizClient struct {
	flat   AnalyticBizFlat
	call   *AnalyticRestateCall
	send   *AnalyticRestateSender
	future *AnalyticRestateFuture
}

var _ AnalyticBizClient = (*analyticBizClient)(nil)

func (c *analyticBizClient) GetProductPopularity(ctx context.Context, spuID uuid.UUID) (analyticdb.AnalyticProductPopularity, error) {
	return c.flat.GetProductPopularity(ctx, spuID)
}

func (c *analyticBizClient) ListTopProductPopularity(ctx context.Context, params paginate.Params) ([]analyticdb.AnalyticProductPopularity, error) {
	return c.flat.ListTopProductPopularity(ctx, params)
}

func (c *analyticBizClient) Call() AnalyticBizCall { return c.call }

func (c *analyticBizClient) Future() AnalyticBizFuture { return c.future }

func (c *analyticBizClient) Send() AnalyticBizSender { return c.send }

// NewAnalyticBizClientInProcess builds a client whose flat queries call the in-process biz.
func NewAnalyticBizClientInProcess(restateIngressURL string, biz AnalyticBiz) AnalyticBizClient {
	return &analyticBizClient{
		flat:   &analyticBizBestEffortLocal{biz: biz},
		call:   NewAnalyticRestateCall(restateIngressURL),
		send:   &AnalyticRestateSender{client: restatec.NewSendClient(restateIngressURL)},
		future: &AnalyticRestateFuture{},
	}
}

// NewAnalyticBizClientRemote builds a client whose flat queries call a remote besteffort server.
func NewAnalyticBizClientRemote(restateIngressURL, bestEffortURL string) AnalyticBizClient {
	return &analyticBizClient{
		flat:   &analyticBizBestEffortRemote{call: besteffort.NewCallClient(bestEffortURL)},
		call:   NewAnalyticRestateCall(restateIngressURL),
		send:   &AnalyticRestateSender{client: restatec.NewSendClient(restateIngressURL)},
		future: &AnalyticRestateFuture{},
	}
}

// RegisterAnalyticBestEffort wires the query methods onto a besteffort HTTP server.
// Commands are served by Restate, not here.
func RegisterAnalyticBestEffort(s *besteffort.Server, biz AnalyticBiz) {
	s.Handle(serviceName, "GetProductPopularity", func(ctx context.Context, body []byte) (any, error) {
		var p uuid.UUID
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, err
		}
		return biz.GetProductPopularity(ctx, p)
	})
	s.Handle(serviceName, "ListTopProductPopularity", func(ctx context.Context, body []byte) (any, error) {
		var p paginate.Params
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, err
		}
		return biz.ListTopProductPopularity(ctx, p)
	})
}
