// Code generated by pgtempl; DO NOT EDIT.
package commondb

import (
	"context"

	"github.com/google/uuid"
	"github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5"

	"shopnexus-server/internal/shared/paginate"
	"shopnexus-server/internal/shared/repolist"
)

// ListResourceReferenceFilter filters "common"."resource_reference". Each slice field is an IN/ANY match;
// *From/*To pairs are inclusive range bounds. Zero value = no filter.
type ListResourceReferenceFilter struct {
	Id        []int64
	RsId      []uuid.UUID
	RefType   []CommonResourceRefType
	RefId     []uuid.UUID
	Order     []int32
	OrderFrom null.Int
	OrderTo   null.Int
}

func resourceReferenceListConds(f ListResourceReferenceFilter, conds *[]string, args pgx.NamedArgs) {
	if len(f.Id) > 0 {
		*conds = append(*conds, `"id" = ANY(@id)`)
		args["id"] = f.Id
	}
	if len(f.RsId) > 0 {
		*conds = append(*conds, `"rs_id" = ANY(@rs_id)`)
		args["rs_id"] = f.RsId
	}
	if len(f.RefType) > 0 {
		*conds = append(*conds, `"ref_type" = ANY(@ref_type)`)
		args["ref_type"] = f.RefType
	}
	if len(f.RefId) > 0 {
		*conds = append(*conds, `"ref_id" = ANY(@ref_id)`)
		args["ref_id"] = f.RefId
	}
	if len(f.Order) > 0 {
		*conds = append(*conds, `"order" = ANY(@order)`)
		args["order"] = f.Order
	}
	if f.OrderFrom.Valid {
		*conds = append(*conds, `"order" >= @order_from`)
		args["order_from"] = f.OrderFrom.Int64
	}
	if f.OrderTo.Valid {
		*conds = append(*conds, `"order" <= @order_to`)
		args["order_to"] = f.OrderTo.Int64
	}
}

func resourceReferenceListSpec(f ListResourceReferenceFilter) repolist.Spec[CommonResourceReference] {
	return repolist.Spec[CommonResourceReference]{
		Table: `"common"."resource_reference"`,
		PK:    "id",
		Whitelist: paginate.Whitelist{
			"id":    {Col: `"id"`, Cast: "int8"},
			"order": {Col: `"order"`, Cast: "int4"},
		},
		BindConds: func(conds *[]string, args pgx.NamedArgs) { resourceReferenceListConds(f, conds, args) },
	}
}

// ListResourceReference runs offset (?page) or cursor (?cursor/?sort) pagination over "common"."resource_reference".
func (q *Queries) ListResourceReference(ctx context.Context, req repolist.Request, f ListResourceReferenceFilter) (paginate.PaginateResult[CommonResourceReference], error) {
	return repolist.List(ctx, q.db, resourceReferenceListSpec(f), req)
}
