// Code generated by pgtempl; DO NOT EDIT.
package commondb

import (
	"context"

	"github.com/google/uuid"
	"github.com/guregu/null/v6"

	"shopnexus-server/internal/shared/paginate"
	"shopnexus-server/internal/shared/repolist"
)

// ListOptionParams filters "common"."option". A slice field is an IN/ANY match: nil = skip,
// non-nil empty = match nothing. *From/*To pairs are inclusive range bounds.
type ListOptionParams struct {
	paginate.Params

	Id           []string
	OwnerId      []uuid.UUID
	IsEnabled    []bool
	Name         []string
	Description  []string
	Priority     []int32
	PriorityFrom null.Int
	PriorityTo   null.Int
	LogoRsId     []uuid.UUID
	Type         []string
	Provider     []string
}

// OptionQuery is the reusable base listing for "common"."option".
func OptionQuery() repolist.Query[CommonOption] {
	return repolist.Query[CommonOption]{
		Table: `"common"."option"`,
		PK:    "id",
		Sort:  []string{"id", "priority"},
		Fields: func(m *CommonOption) map[string]any {
			return map[string]any{
				"id":          &m.ID,
				"owner_id":    &m.OwnerID,
				"is_enabled":  &m.IsEnabled,
				"name":        &m.Name,
				"description": &m.Description,
				"priority":    &m.Priority,
				"logo_rs_id":  &m.LogoRsID,
				"data":        &m.Data,
				"type":        &m.Type,
				"provider":    &m.Provider,
			}
		},
	}
}

// OptionConds maps the filter params to predicates.
func OptionConds(f ListOptionParams) []repolist.Cond {
	return []repolist.Cond{
		repolist.In(`"id"`, f.Id),
		repolist.In(`"owner_id"`, f.OwnerId),
		repolist.In(`"is_enabled"`, f.IsEnabled),
		repolist.In(`"name"`, f.Name),
		repolist.In(`"description"`, f.Description),
		repolist.In(`"priority"`, f.Priority),
		repolist.Gte(`"priority"`, f.PriorityFrom),
		repolist.Lte(`"priority"`, f.PriorityTo),
		repolist.In(`"logo_rs_id"`, f.LogoRsId),
		repolist.In(`"type"`, f.Type),
		repolist.In(`"provider"`, f.Provider),
	}
}

// ListOption runs offset (?page) or cursor (?cursor/?sort) pagination over "common"."option".
func (q *Queries) ListOption(ctx context.Context, f ListOptionParams) (paginate.PaginateResult[CommonOption], error) {
	return repolist.List(ctx, q.db, f.Params, OptionQuery().Filter(OptionConds(f)...))
}
