// Code generated by cmd/nullmarshal. DO NOT EDIT.

package commondb

import "encoding/json"

func (n NullCommonResourceRefType) MarshalJSON() ([]byte, error) {
	if !n.Valid {
		return []byte("null"), nil
	}
	return json.Marshal(n.CommonResourceRefType)
}

func (n *NullCommonResourceRefType) UnmarshalJSON(b []byte) error {
	if string(b) == "null" {
		n.Valid = false
		return nil
	}
	n.Valid = true
	return json.Unmarshal(b, &n.CommonResourceRefType)
}
