apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    url: db:5432
    user: app
    isDefault: true
    jsonData:
      database: shopnexus
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    secureJsonData:
      password: app
