// Code generated by genrestate; DO NOT EDIT.

package inventorybiz

import (
	"context"
	"encoding/json"
	restate "github.com/restatedev/sdk-go"
	inventorydb "shopnexus-server/internal/module/inventory/db/sqlc"
	"shopnexus-server/internal/shared/besteffort"
	"shopnexus-server/internal/shared/paginate"
	restatec "shopnexus-server/internal/shared/restate"
)

const serviceName = "Inventory"

// InventoryBizCall mirrors the command methods of InventoryBiz as request-response calls.
type InventoryBizCall interface {
	UpdateStockSettings(ctx context.Context, params UpdateStockSettingsParams) (inventorydb.InventoryStock, error)
	CreateStock(ctx context.Context, params CreateStockParams) (inventorydb.InventoryStock, error)
	ImportStock(ctx context.Context, params ImportStockParams) error
	ReserveInventory(ctx context.Context, params ReserveInventoryParams) ([]ReserveInventoryResult, error)
	ReleaseInventory(ctx context.Context, params ReleaseInventoryParams) error
	UpdateSerial(ctx context.Context, params UpdateSerialParams) error
}

// InventoryBizSender mirrors the command methods of InventoryBiz as one-way (fire-and-forget) calls.
type InventoryBizSender interface {
	UpdateStockSettings(ctx context.Context, params UpdateStockSettingsParams) error
	CreateStock(ctx context.Context, params CreateStockParams) error
	ImportStock(ctx context.Context, params ImportStockParams) error
	ReserveInventory(ctx context.Context, params ReserveInventoryParams) error
	ReleaseInventory(ctx context.Context, params ReleaseInventoryParams) error
	UpdateSerial(ctx context.Context, params UpdateSerialParams) error
}

// InventoryBizFuture mirrors the command methods of InventoryBiz returning response futures for
// racing or parallel calls. Only usable inside a Restate handler context.
type InventoryBizFuture interface {
	UpdateStockSettings(rctx restate.Context, params UpdateStockSettingsParams) restate.ResponseFuture[inventorydb.InventoryStock]
	CreateStock(rctx restate.Context, params CreateStockParams) restate.ResponseFuture[inventorydb.InventoryStock]
	ImportStock(rctx restate.Context, params ImportStockParams) restate.ResponseFuture[restate.Void]
	ReserveInventory(rctx restate.Context, params ReserveInventoryParams) restate.ResponseFuture[[]ReserveInventoryResult]
	ReleaseInventory(rctx restate.Context, params ReleaseInventoryParams) restate.ResponseFuture[restate.Void]
	UpdateSerial(rctx restate.Context, params UpdateSerialParams) restate.ResponseFuture[restate.Void]
}

// InventoryBizClient is the cross-module client: query methods are flat (non-durable),
// Call()/Future()/Send() reach the durable command surfaces.
type InventoryBizClient interface {
	GetStock(ctx context.Context, params GetStockParams) (inventorydb.InventoryStock, error)
	ListStock(ctx context.Context, params ListStockParams) (paginate.PaginateResult[inventorydb.InventoryStock], error)
	ListStockHistory(ctx context.Context, params ListStockHistoryParams) (paginate.PaginateResult[inventorydb.InventoryStockHistory], error)
	ListSerial(ctx context.Context, params ListSerialParams) (paginate.PaginateResult[inventorydb.InventorySerial], error)
	ListMostTakenSku(ctx context.Context, params ListMostTakenSkuParams) ([]inventorydb.InventoryStock, error)
	Call() InventoryBizCall
	Future() InventoryBizFuture
	Send() InventoryBizSender
}

// InventoryRestateCall implements InventoryBizCall via Restate HTTP ingress.
type InventoryRestateCall struct {
	call *restatec.CallClient
}

var _ InventoryBizCall = (*InventoryRestateCall)(nil)

func NewInventoryRestateCall(restateIngressURL string) *InventoryRestateCall {
	return &InventoryRestateCall{call: restatec.NewCallClient(restateIngressURL)}
}

func (p *InventoryRestateCall) UpdateStockSettings(ctx context.Context, params UpdateStockSettingsParams) (inventorydb.InventoryStock, error) {
	return restatec.Call[inventorydb.InventoryStock](ctx, p.call, serviceName, "UpdateStockSettings", params)
}

func (p *InventoryRestateCall) CreateStock(ctx context.Context, params CreateStockParams) (inventorydb.InventoryStock, error) {
	return restatec.Call[inventorydb.InventoryStock](ctx, p.call, serviceName, "CreateStock", params)
}

func (p *InventoryRestateCall) ImportStock(ctx context.Context, params ImportStockParams) error {
	return restatec.CallVoid(ctx, p.call, serviceName, "ImportStock", params)
}

func (p *InventoryRestateCall) ReserveInventory(ctx context.Context, params ReserveInventoryParams) ([]ReserveInventoryResult, error) {
	return restatec.Call[[]ReserveInventoryResult](ctx, p.call, serviceName, "ReserveInventory", params)
}

func (p *InventoryRestateCall) ReleaseInventory(ctx context.Context, params ReleaseInventoryParams) error {
	return restatec.CallVoid(ctx, p.call, serviceName, "ReleaseInventory", params)
}

func (p *InventoryRestateCall) UpdateSerial(ctx context.Context, params UpdateSerialParams) error {
	return restatec.CallVoid(ctx, p.call, serviceName, "UpdateSerial", params)
}

// InventoryRestateSender implements InventoryBizSender.
type InventoryRestateSender struct {
	client *restatec.SendClient
}

var _ InventoryBizSender = (*InventoryRestateSender)(nil)

func (s *InventoryRestateSender) UpdateStockSettings(ctx context.Context, params UpdateStockSettingsParams) error {
	return restatec.Send(ctx, s.client, serviceName, "UpdateStockSettings", params)
}

func (s *InventoryRestateSender) CreateStock(ctx context.Context, params CreateStockParams) error {
	return restatec.Send(ctx, s.client, serviceName, "CreateStock", params)
}

func (s *InventoryRestateSender) ImportStock(ctx context.Context, params ImportStockParams) error {
	return restatec.Send(ctx, s.client, serviceName, "ImportStock", params)
}

func (s *InventoryRestateSender) ReserveInventory(ctx context.Context, params ReserveInventoryParams) error {
	return restatec.Send(ctx, s.client, serviceName, "ReserveInventory", params)
}

func (s *InventoryRestateSender) ReleaseInventory(ctx context.Context, params ReleaseInventoryParams) error {
	return restatec.Send(ctx, s.client, serviceName, "ReleaseInventory", params)
}

func (s *InventoryRestateSender) UpdateSerial(ctx context.Context, params UpdateSerialParams) error {
	return restatec.Send(ctx, s.client, serviceName, "UpdateSerial", params)
}

// InventoryRestateFuture implements InventoryBizFuture via the Restate SDK.
type InventoryRestateFuture struct{}

var _ InventoryBizFuture = (*InventoryRestateFuture)(nil)

func (f *InventoryRestateFuture) UpdateStockSettings(rctx restate.Context, params UpdateStockSettingsParams) restate.ResponseFuture[inventorydb.InventoryStock] {
	return restate.Service[inventorydb.InventoryStock](rctx, serviceName, "UpdateStockSettings").RequestFuture(params)
}

func (f *InventoryRestateFuture) CreateStock(rctx restate.Context, params CreateStockParams) restate.ResponseFuture[inventorydb.InventoryStock] {
	return restate.Service[inventorydb.InventoryStock](rctx, serviceName, "CreateStock").RequestFuture(params)
}

func (f *InventoryRestateFuture) ImportStock(rctx restate.Context, params ImportStockParams) restate.ResponseFuture[restate.Void] {
	return restate.Service[restate.Void](rctx, serviceName, "ImportStock").RequestFuture(params)
}

func (f *InventoryRestateFuture) ReserveInventory(rctx restate.Context, params ReserveInventoryParams) restate.ResponseFuture[[]ReserveInventoryResult] {
	return restate.Service[[]ReserveInventoryResult](rctx, serviceName, "ReserveInventory").RequestFuture(params)
}

func (f *InventoryRestateFuture) ReleaseInventory(rctx restate.Context, params ReleaseInventoryParams) restate.ResponseFuture[restate.Void] {
	return restate.Service[restate.Void](rctx, serviceName, "ReleaseInventory").RequestFuture(params)
}

func (f *InventoryRestateFuture) UpdateSerial(rctx restate.Context, params UpdateSerialParams) restate.ResponseFuture[restate.Void] {
	return restate.Service[restate.Void](rctx, serviceName, "UpdateSerial").RequestFuture(params)
}

// InventoryService adapts InventoryBiz into restate.Context handlers for restate.Reflect.
type InventoryService struct {
	biz InventoryBiz
}

func NewInventoryService(biz InventoryBiz) *InventoryService { return &InventoryService{biz: biz} }

func (s *InventoryService) ServiceName() string { return serviceName }

func (s *InventoryService) GetStock(ctx restate.Context, params GetStockParams) (inventorydb.InventoryStock, error) {
	return s.biz.GetStock(ctx, params)
}

func (s *InventoryService) UpdateStockSettings(ctx restate.Context, params UpdateStockSettingsParams) (inventorydb.InventoryStock, error) {
	return s.biz.UpdateStockSettings(ctx, params)
}

func (s *InventoryService) ListStock(ctx restate.Context, params ListStockParams) (paginate.PaginateResult[inventorydb.InventoryStock], error) {
	return s.biz.ListStock(ctx, params)
}

func (s *InventoryService) CreateStock(ctx restate.Context, params CreateStockParams) (inventorydb.InventoryStock, error) {
	return s.biz.CreateStock(ctx, params)
}

func (s *InventoryService) ListStockHistory(ctx restate.Context, params ListStockHistoryParams) (paginate.PaginateResult[inventorydb.InventoryStockHistory], error) {
	return s.biz.ListStockHistory(ctx, params)
}

func (s *InventoryService) ImportStock(ctx restate.Context, params ImportStockParams) error {
	return s.biz.ImportStock(ctx, params)
}

func (s *InventoryService) ReserveInventory(ctx restate.Context, params ReserveInventoryParams) ([]ReserveInventoryResult, error) {
	return s.biz.ReserveInventory(ctx, params)
}

func (s *InventoryService) ReleaseInventory(ctx restate.Context, params ReleaseInventoryParams) error {
	return s.biz.ReleaseInventory(ctx, params)
}

func (s *InventoryService) UpdateSerial(ctx restate.Context, params UpdateSerialParams) error {
	return s.biz.UpdateSerial(ctx, params)
}

func (s *InventoryService) ListSerial(ctx restate.Context, params ListSerialParams) (paginate.PaginateResult[inventorydb.InventorySerial], error) {
	return s.biz.ListSerial(ctx, params)
}

func (s *InventoryService) ListMostTakenSku(ctx restate.Context, params ListMostTakenSkuParams) ([]inventorydb.InventoryStock, error) {
	return s.biz.ListMostTakenSku(ctx, params)
}

// InventoryBizFlat is the flat (non-durable query) surface of InventoryBiz.
type InventoryBizFlat interface {
	GetStock(ctx context.Context, params GetStockParams) (inventorydb.InventoryStock, error)
	ListStock(ctx context.Context, params ListStockParams) (paginate.PaginateResult[inventorydb.InventoryStock], error)
	ListStockHistory(ctx context.Context, params ListStockHistoryParams) (paginate.PaginateResult[inventorydb.InventoryStockHistory], error)
	ListSerial(ctx context.Context, params ListSerialParams) (paginate.PaginateResult[inventorydb.InventorySerial], error)
	ListMostTakenSku(ctx context.Context, params ListMostTakenSkuParams) ([]inventorydb.InventoryStock, error)
}

// inventoryBizBestEffortLocal delegates flat queries to the in-process biz.
type inventoryBizBestEffortLocal struct{ biz InventoryBiz }

var _ InventoryBizFlat = (*inventoryBizBestEffortLocal)(nil)

func (b *inventoryBizBestEffortLocal) GetStock(ctx context.Context, params GetStockParams) (inventorydb.InventoryStock, error) {
	return b.biz.GetStock(ctx, params)
}

func (b *inventoryBizBestEffortLocal) ListStock(ctx context.Context, params ListStockParams) (paginate.PaginateResult[inventorydb.InventoryStock], error) {
	return b.biz.ListStock(ctx, params)
}

func (b *inventoryBizBestEffortLocal) ListStockHistory(ctx context.Context, params ListStockHistoryParams) (paginate.PaginateResult[inventorydb.InventoryStockHistory], error) {
	return b.biz.ListStockHistory(ctx, params)
}

func (b *inventoryBizBestEffortLocal) ListSerial(ctx context.Context, params ListSerialParams) (paginate.PaginateResult[inventorydb.InventorySerial], error) {
	return b.biz.ListSerial(ctx, params)
}

func (b *inventoryBizBestEffortLocal) ListMostTakenSku(ctx context.Context, params ListMostTakenSkuParams) ([]inventorydb.InventoryStock, error) {
	return b.biz.ListMostTakenSku(ctx, params)
}

// inventoryBizBestEffortRemote routes flat queries over HTTP/2.
type inventoryBizBestEffortRemote struct{ call *besteffort.CallClient }

var _ InventoryBizFlat = (*inventoryBizBestEffortRemote)(nil)

func (b *inventoryBizBestEffortRemote) GetStock(ctx context.Context, params GetStockParams) (inventorydb.InventoryStock, error) {
	return besteffort.Call[inventorydb.InventoryStock](ctx, b.call, serviceName, "GetStock", params)
}

func (b *inventoryBizBestEffortRemote) ListStock(ctx context.Context, params ListStockParams) (paginate.PaginateResult[inventorydb.InventoryStock], error) {
	return besteffort.Call[paginate.PaginateResult[inventorydb.InventoryStock]](ctx, b.call, serviceName, "ListStock", params)
}

func (b *inventoryBizBestEffortRemote) ListStockHistory(ctx context.Context, params ListStockHistoryParams) (paginate.PaginateResult[inventorydb.InventoryStockHistory], error) {
	return besteffort.Call[paginate.PaginateResult[inventorydb.InventoryStockHistory]](ctx, b.call, serviceName, "ListStockHistory", params)
}

func (b *inventoryBizBestEffortRemote) ListSerial(ctx context.Context, params ListSerialParams) (paginate.PaginateResult[inventorydb.InventorySerial], error) {
	return besteffort.Call[paginate.PaginateResult[inventorydb.InventorySerial]](ctx, b.call, serviceName, "ListSerial", params)
}

func (b *inventoryBizBestEffortRemote) ListMostTakenSku(ctx context.Context, params ListMostTakenSkuParams) ([]inventorydb.InventoryStock, error) {
	return besteffort.Call[[]inventorydb.InventoryStock](ctx, b.call, serviceName, "ListMostTakenSku", params)
}

// inventoryBizClient holds the flat query impl and the durable command proxies.
type inventoryBizClient struct {
	flat   InventoryBizFlat
	call   *InventoryRestateCall
	send   *InventoryRestateSender
	future *InventoryRestateFuture
}

var _ InventoryBizClient = (*inventoryBizClient)(nil)

func (c *inventoryBizClient) GetStock(ctx context.Context, params GetStockParams) (inventorydb.InventoryStock, error) {
	return c.flat.GetStock(ctx, params)
}

func (c *inventoryBizClient) ListStock(ctx context.Context, params ListStockParams) (paginate.PaginateResult[inventorydb.InventoryStock], error) {
	return c.flat.ListStock(ctx, params)
}

func (c *inventoryBizClient) ListStockHistory(ctx context.Context, params ListStockHistoryParams) (paginate.PaginateResult[inventorydb.InventoryStockHistory], error) {
	return c.flat.ListStockHistory(ctx, params)
}

func (c *inventoryBizClient) ListSerial(ctx context.Context, params ListSerialParams) (paginate.PaginateResult[inventorydb.InventorySerial], error) {
	return c.flat.ListSerial(ctx, params)
}

func (c *inventoryBizClient) ListMostTakenSku(ctx context.Context, params ListMostTakenSkuParams) ([]inventorydb.InventoryStock, error) {
	return c.flat.ListMostTakenSku(ctx, params)
}

func (c *inventoryBizClient) Call() InventoryBizCall { return c.call }

func (c *inventoryBizClient) Future() InventoryBizFuture { return c.future }

func (c *inventoryBizClient) Send() InventoryBizSender { return c.send }

// NewInventoryBizClientInProcess builds a client whose flat queries call the in-process biz.
func NewInventoryBizClientInProcess(restateIngressURL string, biz InventoryBiz) InventoryBizClient {
	return &inventoryBizClient{
		flat:   &inventoryBizBestEffortLocal{biz: biz},
		call:   NewInventoryRestateCall(restateIngressURL),
		send:   &InventoryRestateSender{client: restatec.NewSendClient(restateIngressURL)},
		future: &InventoryRestateFuture{},
	}
}

// NewInventoryBizClientRemote builds a client whose flat queries call a remote besteffort server.
func NewInventoryBizClientRemote(restateIngressURL, bestEffortURL string) InventoryBizClient {
	return &inventoryBizClient{
		flat:   &inventoryBizBestEffortRemote{call: besteffort.NewCallClient(bestEffortURL)},
		call:   NewInventoryRestateCall(restateIngressURL),
		send:   &InventoryRestateSender{client: restatec.NewSendClient(restateIngressURL)},
		future: &InventoryRestateFuture{},
	}
}

// RegisterInventoryBestEffort wires the query methods onto a besteffort HTTP server.
// Commands are served by Restate, not here.
func RegisterInventoryBestEffort(s *besteffort.Server, biz InventoryBiz) {
	s.Handle(serviceName, "GetStock", func(ctx context.Context, body []byte) (any, error) {
		var p GetStockParams
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, err
		}
		return biz.GetStock(ctx, p)
	})
	s.Handle(serviceName, "ListStock", func(ctx context.Context, body []byte) (any, error) {
		var p ListStockParams
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, err
		}
		return biz.ListStock(ctx, p)
	})
	s.Handle(serviceName, "ListStockHistory", func(ctx context.Context, body []byte) (any, error) {
		var p ListStockHistoryParams
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, err
		}
		return biz.ListStockHistory(ctx, p)
	})
	s.Handle(serviceName, "ListSerial", func(ctx context.Context, body []byte) (any, error) {
		var p ListSerialParams
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, err
		}
		return biz.ListSerial(ctx, p)
	})
	s.Handle(serviceName, "ListMostTakenSku", func(ctx context.Context, body []byte) (any, error) {
		var p ListMostTakenSkuParams
		if err := json.Unmarshal(body, &p); err != nil {
			return nil, err
		}
		return biz.ListMostTakenSku(ctx, p)
	})
}
