// Code generated by pgtempl; DO NOT EDIT.
package inventorydb

import (
	"context"
	"time"

	"github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5"

	"shopnexus-server/internal/shared/paginate"
	"shopnexus-server/internal/shared/repolist"
)

// ListStockHistoryParams filters "inventory"."stock_history". Each slice field is an IN/ANY match;
// *From/*To pairs are inclusive range bounds. Zero value = no filter.
type ListStockHistoryParams struct {
	paginate.Params

	Id              []int64
	StockId         []int64
	Change          []int64
	ChangeFrom      null.Int
	ChangeTo        null.Int
	DateCreated     []time.Time
	DateCreatedFrom null.Time
	DateCreatedTo   null.Time
}

func stockHistoryListConds(f ListStockHistoryParams, conds *[]string, args pgx.NamedArgs) {
	if len(f.Id) > 0 {
		*conds = append(*conds, `"id" = ANY(@id)`)
		args["id"] = f.Id
	}
	if len(f.StockId) > 0 {
		*conds = append(*conds, `"stock_id" = ANY(@stock_id)`)
		args["stock_id"] = f.StockId
	}
	if len(f.Change) > 0 {
		*conds = append(*conds, `"change" = ANY(@change)`)
		args["change"] = f.Change
	}
	if f.ChangeFrom.Valid {
		*conds = append(*conds, `"change" >= @change_from`)
		args["change_from"] = f.ChangeFrom.Int64
	}
	if f.ChangeTo.Valid {
		*conds = append(*conds, `"change" <= @change_to`)
		args["change_to"] = f.ChangeTo.Int64
	}
	if len(f.DateCreated) > 0 {
		*conds = append(*conds, `"date_created" = ANY(@date_created)`)
		args["date_created"] = f.DateCreated
	}
	if f.DateCreatedFrom.Valid {
		*conds = append(*conds, `"date_created" >= @date_created_from`)
		args["date_created_from"] = f.DateCreatedFrom.Time
	}
	if f.DateCreatedTo.Valid {
		*conds = append(*conds, `"date_created" <= @date_created_to`)
		args["date_created_to"] = f.DateCreatedTo.Time
	}
}

func stockHistoryListSpec(f ListStockHistoryParams) repolist.Spec[InventoryStockHistory] {
	return repolist.Spec[InventoryStockHistory]{
		Table: `"inventory"."stock_history"`,
		PK:    "id",
		Whitelist: paginate.Whitelist{
			"id":           {Col: `"id"`, Cast: "int8"},
			"change":       {Col: `"change"`, Cast: "int8"},
			"date_created": {Col: `"date_created"`, Cast: "timestamptz"},
		},
		BindConds: func(conds *[]string, args pgx.NamedArgs) { stockHistoryListConds(f, conds, args) },
	}
}

// ListStockHistory runs offset (?page) or cursor (?cursor/?sort) pagination over "inventory"."stock_history".
func (q *Queries) ListStockHistory(ctx context.Context, f ListStockHistoryParams) (paginate.PaginateResult[InventoryStockHistory], error) {
	return repolist.List(ctx, q.db, stockHistoryListSpec(f), f.Params)
}
