// Code generated by pgtempl; DO NOT EDIT.
package inventorydb

import (
	"context"
	"time"

	"github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5"

	"shopnexus-server/internal/shared/paginate"
	"shopnexus-server/internal/shared/repolist"
)

// ListSerialParams filters "inventory"."serial". A slice field is an IN/ANY match: nil = skip,
// non-nil empty = match nothing. *From/*To pairs are inclusive range bounds.
type ListSerialParams struct {
	paginate.Params

	Id              []string
	StockId         []int64
	Status          []InventoryStatus
	DateCreated     []time.Time
	DateCreatedFrom null.Time
	DateCreatedTo   null.Time
}

func serialListConds(f ListSerialParams, conds *[]string, args pgx.NamedArgs) {
	if f.Id != nil {
		*conds = append(*conds, `"id" = ANY(@id)`)
		args["id"] = f.Id
	}
	if f.StockId != nil {
		*conds = append(*conds, `"stock_id" = ANY(@stock_id)`)
		args["stock_id"] = f.StockId
	}
	if f.Status != nil {
		*conds = append(*conds, `"status" = ANY(@status)`)
		args["status"] = f.Status
	}
	if f.DateCreated != nil {
		*conds = append(*conds, `"date_created" = ANY(@date_created)`)
		args["date_created"] = f.DateCreated
	}
	if f.DateCreatedFrom.Valid {
		*conds = append(*conds, `"date_created" >= @date_created_from`)
		args["date_created_from"] = f.DateCreatedFrom.Time
	}
	if f.DateCreatedTo.Valid {
		*conds = append(*conds, `"date_created" <= @date_created_to`)
		args["date_created_to"] = f.DateCreatedTo.Time
	}
}

func serialListSpec(f ListSerialParams) repolist.Spec[InventorySerial] {
	return repolist.Spec[InventorySerial]{
		Table: `"inventory"."serial"`,
		PK:    "id",
		Whitelist: paginate.Whitelist{
			"id":           {Col: `"id"`, Cast: "text"},
			"date_created": {Col: `"date_created"`, Cast: "timestamptz"},
		},
		BindConds: func(conds *[]string, args pgx.NamedArgs) { serialListConds(f, conds, args) },
	}
}

// ListSerial runs offset (?page) or cursor (?cursor/?sort) pagination over "inventory"."serial".
func (q *Queries) ListSerial(ctx context.Context, f ListSerialParams) (paginate.PaginateResult[InventorySerial], error) {
	return repolist.List(ctx, q.db, serialListSpec(f), f.Params)
}
