// Code generated by pgtempl; DO NOT EDIT.
package inventorydb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5"

	"shopnexus-server/internal/shared/paginate"
	"shopnexus-server/internal/shared/repolist"
)

// ListStockFilter filters "inventory"."stock". Each slice field is an IN/ANY match;
// *From/*To pairs are inclusive range bounds. Zero value = no filter.
type ListStockFilter struct {
	Id              []int64
	RefType         []InventoryStockRefType
	RefId           []uuid.UUID
	Stock           []int64
	StockFrom       null.Int
	StockTo         null.Int
	Taken           []int64
	TakenFrom       null.Int
	TakenTo         null.Int
	SerialRequired  []bool
	DateCreated     []time.Time
	DateCreatedFrom null.Time
	DateCreatedTo   null.Time
}

func stockListConds(f ListStockFilter, conds *[]string, args pgx.NamedArgs) {
	if len(f.Id) > 0 {
		*conds = append(*conds, `"id" = ANY(@id)`)
		args["id"] = f.Id
	}
	if len(f.RefType) > 0 {
		*conds = append(*conds, `"ref_type" = ANY(@ref_type)`)
		args["ref_type"] = f.RefType
	}
	if len(f.RefId) > 0 {
		*conds = append(*conds, `"ref_id" = ANY(@ref_id)`)
		args["ref_id"] = f.RefId
	}
	if len(f.Stock) > 0 {
		*conds = append(*conds, `"stock" = ANY(@stock)`)
		args["stock"] = f.Stock
	}
	if f.StockFrom.Valid {
		*conds = append(*conds, `"stock" >= @stock_from`)
		args["stock_from"] = f.StockFrom.Int64
	}
	if f.StockTo.Valid {
		*conds = append(*conds, `"stock" <= @stock_to`)
		args["stock_to"] = f.StockTo.Int64
	}
	if len(f.Taken) > 0 {
		*conds = append(*conds, `"taken" = ANY(@taken)`)
		args["taken"] = f.Taken
	}
	if f.TakenFrom.Valid {
		*conds = append(*conds, `"taken" >= @taken_from`)
		args["taken_from"] = f.TakenFrom.Int64
	}
	if f.TakenTo.Valid {
		*conds = append(*conds, `"taken" <= @taken_to`)
		args["taken_to"] = f.TakenTo.Int64
	}
	if len(f.SerialRequired) > 0 {
		*conds = append(*conds, `"serial_required" = ANY(@serial_required)`)
		args["serial_required"] = f.SerialRequired
	}
	if len(f.DateCreated) > 0 {
		*conds = append(*conds, `"date_created" = ANY(@date_created)`)
		args["date_created"] = f.DateCreated
	}
	if f.DateCreatedFrom.Valid {
		*conds = append(*conds, `"date_created" >= @date_created_from`)
		args["date_created_from"] = f.DateCreatedFrom.Time
	}
	if f.DateCreatedTo.Valid {
		*conds = append(*conds, `"date_created" <= @date_created_to`)
		args["date_created_to"] = f.DateCreatedTo.Time
	}
}

func stockListSpec(f ListStockFilter) repolist.Spec[InventoryStock] {
	return repolist.Spec[InventoryStock]{
		Table: `"inventory"."stock"`,
		PK:    "id",
		Whitelist: paginate.Whitelist{
			"id":           {Col: `"id"`, Cast: "int8"},
			"stock":        {Col: `"stock"`, Cast: "int8"},
			"taken":        {Col: `"taken"`, Cast: "int8"},
			"date_created": {Col: `"date_created"`, Cast: "timestamptz"},
		},
		BindConds: func(conds *[]string, args pgx.NamedArgs) { stockListConds(f, conds, args) },
	}
}

// ListStock runs offset (?page) or cursor (?cursor/?sort) pagination over "inventory"."stock".
func (q *Queries) ListStock(ctx context.Context, req repolist.Request, f ListStockFilter) (paginate.PaginateResult[InventoryStock], error) {
	return repolist.List(ctx, q.db, stockListSpec(f), req)
}
