// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package analyticdb

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

type AnalyticInteractionRefType string

const (
	AnalyticInteractionRefTypeProduct  AnalyticInteractionRefType = "Product"
	AnalyticInteractionRefTypeCategory AnalyticInteractionRefType = "Category"
)

func (e *AnalyticInteractionRefType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnalyticInteractionRefType(s)
	case string:
		*e = AnalyticInteractionRefType(s)
	default:
		return fmt.Errorf("unsupported scan type for AnalyticInteractionRefType: %T", src)
	}
	return nil
}

type NullAnalyticInteractionRefType struct {
	AnalyticInteractionRefType AnalyticInteractionRefType `json:"analytic_interaction_ref_type"`
	Valid                      bool                       `json:"valid"` // Valid is true if AnalyticInteractionRefType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnalyticInteractionRefType) Scan(value interface{}) error {
	if value == nil {
		ns.AnalyticInteractionRefType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnalyticInteractionRefType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnalyticInteractionRefType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnalyticInteractionRefType), nil
}

func (e AnalyticInteractionRefType) Valid() bool {
	switch e {
	case AnalyticInteractionRefTypeProduct,
		AnalyticInteractionRefTypeCategory:
		return true
	}
	return false
}

func AllAnalyticInteractionRefTypeValues() []AnalyticInteractionRefType {
	return []AnalyticInteractionRefType{
		AnalyticInteractionRefTypeProduct,
		AnalyticInteractionRefTypeCategory,
	}
}

type AnalyticInteraction struct {
	ID          int64                      `db:"id" json:"id"`
	AccountID   uuid.NullUUID              `db:"account_id" json:"account_id"`
	SessionID   null.String                `db:"session_id" json:"session_id"`
	EventType   string                     `db:"event_type" json:"event_type"`
	RefType     AnalyticInteractionRefType `db:"ref_type" json:"ref_type"`
	RefID       string                     `db:"ref_id" json:"ref_id"`
	Metadata    json.RawMessage            `db:"metadata" json:"metadata"`
	UserAgent   null.String                `db:"user_agent" json:"user_agent"`
	IpAddress   null.String                `db:"ip_address" json:"ip_address"`
	DateCreated time.Time                  `db:"date_created" json:"date_created"`
}

type AnalyticProductPopularity struct {
	ID            uuid.UUID `db:"id" json:"id"`
	Score         float64   `db:"score" json:"score"`
	ViewCount     int64     `db:"view_count" json:"view_count"`
	PurchaseCount int64     `db:"purchase_count" json:"purchase_count"`
	FavoriteCount int64     `db:"favorite_count" json:"favorite_count"`
	CartCount     int64     `db:"cart_count" json:"cart_count"`
	ReviewCount   int64     `db:"review_count" json:"review_count"`
	DateUpdated   time.Time `db:"date_updated" json:"date_updated"`
}
