// Code generated by genenum; DO NOT EDIT.

package ordermodel

import "encoding/json"

func (e Status) Valid() bool {
	switch e {
	case StatusPending, StatusProcessing, StatusSuccess, StatusCancelled, StatusFailed:
		return true
	}
	return false
}

type NullStatus struct {
	Value Status `json:"value"`
	Valid bool   `json:"valid"`
}

func (n NullStatus) MarshalJSON() ([]byte, error) {
	if !n.Valid {
		return []byte("null"), nil
	}
	return json.Marshal(n.Value)
}

func (n *NullStatus) UnmarshalJSON(b []byte) error {
	if string(b) == "null" {
		n.Valid = false
		return nil
	}
	n.Valid = true
	return json.Unmarshal(b, &n.Value)
}

func (e DisputeStatus) Valid() bool {
	switch e {
	case DisputeStatusOpen, DisputeStatusSellerWins, DisputeStatusBuyerWins:
		return true
	}
	return false
}

type NullDisputeStatus struct {
	Value DisputeStatus `json:"value"`
	Valid bool          `json:"valid"`
}

func (n NullDisputeStatus) MarshalJSON() ([]byte, error) {
	if !n.Valid {
		return []byte("null"), nil
	}
	return json.Marshal(n.Value)
}

func (n *NullDisputeStatus) UnmarshalJSON(b []byte) error {
	if string(b) == "null" {
		n.Valid = false
		return nil
	}
	n.Valid = true
	return json.Unmarshal(b, &n.Value)
}
