// Code generated by genenum; DO NOT EDIT.

package ordermodel

import "encoding/json"

func (e RefundStatus) Valid() bool {
	switch e {
	case RefundStatusShipping, RefundStatusAwaitingSellerReview, RefundStatusDisputed, RefundStatusAccepted, RefundStatusRejected, RefundStatusCancelled:
		return true
	}
	return false
}

type NullRefundStatus struct {
	Value RefundStatus `json:"value"`
	Valid bool         `json:"valid"`
}

func (n NullRefundStatus) MarshalJSON() ([]byte, error) {
	if !n.Valid {
		return []byte("null"), nil
	}
	return json.Marshal(n.Value)
}

func (n *NullRefundStatus) UnmarshalJSON(b []byte) error {
	if string(b) == "null" {
		n.Valid = false
		return nil
	}
	n.Valid = true
	return json.Unmarshal(b, &n.Value)
}
