// Code generated by pgtempl; DO NOT EDIT.
package catalogdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guregu/null/v6"

	"shopnexus-server/internal/shared/paginate"
	"shopnexus-server/internal/shared/repolist"
)

// ListProductSkuParams filters "catalog"."product_sku". A slice field is an IN/ANY match: nil = skip,
// non-nil empty = match nothing. *From/*To pairs are inclusive range bounds.
type ListProductSkuParams struct {
	paginate.Params

	Id              []uuid.UUID
	SpuId           []uuid.UUID
	Price           []int64
	PriceFrom       null.Int
	PriceTo         null.Int
	SharedPackaging []bool
	DateCreated     []time.Time
	DateCreatedFrom null.Time
	DateCreatedTo   null.Time
	DateDeleted     []time.Time
	DateDeletedFrom null.Time
	DateDeletedTo   null.Time
}

// ProductSkuQuery is the reusable base listing for "catalog"."product_sku".
func ProductSkuQuery() repolist.Query[CatalogProductSku] {
	return repolist.Query[CatalogProductSku]{
		Table: `"catalog"."product_sku"`,
		PK:    "id",
		Sort:  []string{"id", "price", "date_created"},
		Fields: func(m *CatalogProductSku) map[string]any {
			return map[string]any{
				"id":               &m.ID,
				"spu_id":           &m.SpuID,
				"price":            &m.Price,
				"shared_packaging": &m.SharedPackaging,
				"attributes":       &m.Attributes,
				"package_details":  &m.PackageDetails,
				"date_created":     &m.DateCreated,
				"date_deleted":     &m.DateDeleted,
			}
		},
	}
}

// ProductSkuConds maps the filter params to predicates.
func ProductSkuConds(f ListProductSkuParams) []repolist.Cond {
	return []repolist.Cond{
		repolist.In(`"id"`, f.Id),
		repolist.In(`"spu_id"`, f.SpuId),
		repolist.In(`"price"`, f.Price),
		repolist.Gte(`"price"`, f.PriceFrom),
		repolist.Lte(`"price"`, f.PriceTo),
		repolist.In(`"shared_packaging"`, f.SharedPackaging),
		repolist.In(`"date_created"`, f.DateCreated),
		repolist.Gte(`"date_created"`, f.DateCreatedFrom),
		repolist.Lte(`"date_created"`, f.DateCreatedTo),
		repolist.In(`"date_deleted"`, f.DateDeleted),
		repolist.Gte(`"date_deleted"`, f.DateDeletedFrom),
		repolist.Lte(`"date_deleted"`, f.DateDeletedTo),
	}
}

// ListProductSku runs offset (?page) or cursor (?cursor/?sort) pagination over "catalog"."product_sku".
func (q *Queries) ListProductSku(ctx context.Context, f ListProductSkuParams) (paginate.PaginateResult[CatalogProductSku], error) {
	return repolist.List(ctx, q.db, f.Params, ProductSkuQuery().Filter(ProductSkuConds(f)...))
}
