// Code generated by pgtempl; DO NOT EDIT.
package catalogdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guregu/null/v6"

	"shopnexus-server/internal/shared/paginate"
	"shopnexus-server/internal/shared/repolist"
)

// ListSearchSyncParams filters "catalog"."search_sync". A slice field is an IN/ANY match: nil = skip,
// non-nil empty = match nothing. *From/*To pairs are inclusive range bounds.
type ListSearchSyncParams struct {
	paginate.Params

	Id               []int64
	RefType          []CatalogSearchSyncRefType
	RefId            []uuid.UUID
	IsStaleEmbedding []bool
	DateCreated      []time.Time
	DateCreatedFrom  null.Time
	DateCreatedTo    null.Time
	DateUpdated      []time.Time
	DateUpdatedFrom  null.Time
	DateUpdatedTo    null.Time
}

// SearchSyncQuery is the reusable base listing for "catalog"."search_sync".
func SearchSyncQuery() repolist.Query[CatalogSearchSync] {
	return repolist.Query[CatalogSearchSync]{
		Table: `"catalog"."search_sync"`,
		PK:    "id",
		Sort:  []string{"id", "date_created", "date_updated"},
		Fields: func(m *CatalogSearchSync) map[string]any {
			return map[string]any{
				"id":                 &m.ID,
				"ref_type":           &m.RefType,
				"ref_id":             &m.RefID,
				"is_stale_embedding": &m.IsStaleEmbedding,
				"date_created":       &m.DateCreated,
				"date_updated":       &m.DateUpdated,
			}
		},
	}
}

// SearchSyncConds maps the filter params to predicates.
func SearchSyncConds(f ListSearchSyncParams) []repolist.Cond {
	return []repolist.Cond{
		repolist.In(`"id"`, f.Id),
		repolist.In(`"ref_type"`, f.RefType),
		repolist.In(`"ref_id"`, f.RefId),
		repolist.In(`"is_stale_embedding"`, f.IsStaleEmbedding),
		repolist.In(`"date_created"`, f.DateCreated),
		repolist.Gte(`"date_created"`, f.DateCreatedFrom),
		repolist.Lte(`"date_created"`, f.DateCreatedTo),
		repolist.In(`"date_updated"`, f.DateUpdated),
		repolist.Gte(`"date_updated"`, f.DateUpdatedFrom),
		repolist.Lte(`"date_updated"`, f.DateUpdatedTo),
	}
}

// ListSearchSync runs offset (?page) or cursor (?cursor/?sort) pagination over "catalog"."search_sync".
func (q *Queries) ListSearchSync(ctx context.Context, f ListSearchSyncParams) (paginate.PaginateResult[CatalogSearchSync], error) {
	return repolist.List(ctx, q.db, f.Params, SearchSyncQuery().Filter(SearchSyncConds(f)...))
}
