// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: embedding_custom.sql

package catalogdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

const getProductVectors = `-- name: GetProductVectors :many
SELECT spu_id, embedding
FROM catalog.product_embedding
WHERE spu_id = ANY($1::uuid[]) AND embedding IS NOT NULL
`

type GetProductVectorsRow struct {
	SpuID     uuid.UUID       `db:"spu_id" json:"spu_id"`
	Embedding pgvector.Vector `db:"embedding" json:"embedding"`
}

func (q *Queries) GetProductVectors(ctx context.Context, spuIds []uuid.UUID) ([]GetProductVectorsRow, error) {
	rows, err := q.db.Query(ctx, getProductVectors, spuIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductVectorsRow{}
	for rows.Next() {
		var i GetProductVectorsRow
		if err := rows.Scan(&i.SpuID, &i.Embedding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountInterest = `-- name: ListAccountInterest :many
SELECT account_id, slot, embedding, strength
FROM catalog.account_interest
WHERE account_id = ANY($1::uuid[])
ORDER BY account_id, slot
`

type ListAccountInterestRow struct {
	AccountID uuid.UUID       `db:"account_id" json:"account_id"`
	Slot      int16           `db:"slot" json:"slot"`
	Embedding pgvector.Vector `db:"embedding" json:"embedding"`
	Strength  float32         `db:"strength" json:"strength"`
}

func (q *Queries) ListAccountInterest(ctx context.Context, accountIds []uuid.UUID) ([]ListAccountInterestRow, error) {
	rows, err := q.db.Query(ctx, listAccountInterest, accountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountInterestRow{}
	for rows.Next() {
		var i ListAccountInterestRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Slot,
			&i.Embedding,
			&i.Strength,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProductByVector = `-- name: SearchProductByVector :many

SELECT pe.spu_id, (1 - (pe.embedding <=> $1::vector))::float4 AS score
FROM catalog.product_embedding pe
JOIN catalog.product_spu spu ON spu.id = pe.spu_id
WHERE pe.embedding IS NOT NULL AND spu.is_enabled = true AND spu.date_deleted IS NULL
ORDER BY pe.embedding <=> $1::vector
LIMIT $2::int
`

type SearchProductByVectorParams struct {
	Query pgvector.Vector `db:"query" json:"query"`
	Limit int32           `db:"limit" json:"limit"`
}

type SearchProductByVectorRow struct {
	SpuID uuid.UUID `db:"spu_id" json:"spu_id"`
	Score float32   `db:"score" json:"score"`
}

// HybridSearchProduct is hand-written (CTEs + score fusion + pagination/count);
// see internal/module/catalog/db/sqlc/embedding_search.go.
// Single dense ANN over active products (used per interest slot for recommendations).
func (q *Queries) SearchProductByVector(ctx context.Context, arg SearchProductByVectorParams) ([]SearchProductByVectorRow, error) {
	rows, err := q.db.Query(ctx, searchProductByVector, arg.Query, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProductByVectorRow{}
	for rows.Next() {
		var i SearchProductByVectorRow
		if err := rows.Scan(&i.SpuID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
