// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generated_queries.sql

package catalogdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

const countCategory = `-- name: CountCategory :one
SELECT COUNT(*)
FROM "catalog"."category"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("name" = ANY($2) OR $2 IS NULL) AND
    ("description" = ANY($3) OR $3 IS NULL) AND
    ("parent_id" = ANY($4) OR $4 IS NULL)
)
`

type CountCategoryParams struct {
	ID          []uuid.UUID     `db:"id" json:"id"`
	Name        []string        `db:"name" json:"name"`
	Description []string        `db:"description" json:"description"`
	ParentID    []uuid.NullUUID `db:"parent_id" json:"parent_id"`
}

func (q *Queries) CountCategory(ctx context.Context, arg CountCategoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ParentID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countComment = `-- name: CountComment :one
SELECT COUNT(*)
FROM "catalog"."comment"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("account_id" = ANY($2) OR $2 IS NULL) AND
    ("order_id" = ANY($3) OR $3 IS NULL) AND
    ("ref_type" = ANY($4) OR $4 IS NULL) AND
    ("ref_id" = ANY($5) OR $5 IS NULL) AND
    ("body" = ANY($6) OR $6 IS NULL) AND
    ("upvote" = ANY($7) OR $7 IS NULL) AND
    ("upvote" >= $8 OR $8 IS NULL) AND
    ("upvote" <= $9 OR $9 IS NULL) AND
    ("downvote" = ANY($10) OR $10 IS NULL) AND
    ("downvote" >= $11 OR $11 IS NULL) AND
    ("downvote" <= $12 OR $12 IS NULL) AND
    ("score" = ANY($13) OR $13 IS NULL) AND
    ("score" >= $14 OR $14 IS NULL) AND
    ("score" <= $15 OR $15 IS NULL) AND
    ("date_created" = ANY($16) OR $16 IS NULL) AND
    ("date_created" >= $17 OR $17 IS NULL) AND
    ("date_created" <= $18 OR $18 IS NULL) AND
    ("date_updated" = ANY($19) OR $19 IS NULL) AND
    ("date_updated" >= $20 OR $20 IS NULL) AND
    ("date_updated" <= $21 OR $21 IS NULL)
)
`

type CountCommentParams struct {
	ID              []uuid.UUID             `db:"id" json:"id"`
	AccountID       []uuid.UUID             `db:"account_id" json:"account_id"`
	OrderID         []uuid.NullUUID         `db:"order_id" json:"order_id"`
	RefType         []CatalogCommentRefType `db:"ref_type" json:"ref_type"`
	RefID           []uuid.UUID             `db:"ref_id" json:"ref_id"`
	Body            []string                `db:"body" json:"body"`
	Upvote          []int64                 `db:"upvote" json:"upvote"`
	UpvoteFrom      null.Int                `db:"upvote_from" json:"upvote_from"`
	UpvoteTo        null.Int                `db:"upvote_to" json:"upvote_to"`
	Downvote        []int64                 `db:"downvote" json:"downvote"`
	DownvoteFrom    null.Int                `db:"downvote_from" json:"downvote_from"`
	DownvoteTo      null.Int                `db:"downvote_to" json:"downvote_to"`
	Score           []float64               `db:"score" json:"score"`
	ScoreFrom       null.Float              `db:"score_from" json:"score_from"`
	ScoreTo         null.Float              `db:"score_to" json:"score_to"`
	DateCreated     []time.Time             `db:"date_created" json:"date_created"`
	DateCreatedFrom null.Time               `db:"date_created_from" json:"date_created_from"`
	DateCreatedTo   null.Time               `db:"date_created_to" json:"date_created_to"`
	DateUpdated     []time.Time             `db:"date_updated" json:"date_updated"`
	DateUpdatedFrom null.Time               `db:"date_updated_from" json:"date_updated_from"`
	DateUpdatedTo   null.Time               `db:"date_updated_to" json:"date_updated_to"`
}

func (q *Queries) CountComment(ctx context.Context, arg CountCommentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countComment,
		arg.ID,
		arg.AccountID,
		arg.OrderID,
		arg.RefType,
		arg.RefID,
		arg.Body,
		arg.Upvote,
		arg.UpvoteFrom,
		arg.UpvoteTo,
		arg.Downvote,
		arg.DownvoteFrom,
		arg.DownvoteTo,
		arg.Score,
		arg.ScoreFrom,
		arg.ScoreTo,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductSku = `-- name: CountProductSku :one
SELECT COUNT(*)
FROM "catalog"."product_sku"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("spu_id" = ANY($2) OR $2 IS NULL) AND
    ("price" = ANY($3) OR $3 IS NULL) AND
    ("price" >= $4 OR $4 IS NULL) AND
    ("price" <= $5 OR $5 IS NULL) AND
    ("shared_packaging" = ANY($6) OR $6 IS NULL) AND
    ("attributes" = ANY($7) OR $7 IS NULL) AND
    ("package_details" = ANY($8) OR $8 IS NULL) AND
    ("date_created" = ANY($9) OR $9 IS NULL) AND
    ("date_created" >= $10 OR $10 IS NULL) AND
    ("date_created" <= $11 OR $11 IS NULL) AND
    ("date_deleted" = ANY($12) OR $12 IS NULL) AND
    ("date_deleted" >= $13 OR $13 IS NULL) AND
    ("date_deleted" <= $14 OR $14 IS NULL)
)
`

type CountProductSkuParams struct {
	ID              []uuid.UUID       `db:"id" json:"id"`
	SpuID           []uuid.UUID       `db:"spu_id" json:"spu_id"`
	Price           []int64           `db:"price" json:"price"`
	PriceFrom       null.Int          `db:"price_from" json:"price_from"`
	PriceTo         null.Int          `db:"price_to" json:"price_to"`
	SharedPackaging []bool            `db:"shared_packaging" json:"shared_packaging"`
	Attributes      []json.RawMessage `db:"attributes" json:"attributes"`
	PackageDetails  []json.RawMessage `db:"package_details" json:"package_details"`
	DateCreated     []time.Time       `db:"date_created" json:"date_created"`
	DateCreatedFrom null.Time         `db:"date_created_from" json:"date_created_from"`
	DateCreatedTo   null.Time         `db:"date_created_to" json:"date_created_to"`
	DateDeleted     []null.Time       `db:"date_deleted" json:"date_deleted"`
	DateDeletedFrom null.Time         `db:"date_deleted_from" json:"date_deleted_from"`
	DateDeletedTo   null.Time         `db:"date_deleted_to" json:"date_deleted_to"`
}

func (q *Queries) CountProductSku(ctx context.Context, arg CountProductSkuParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductSku,
		arg.ID,
		arg.SpuID,
		arg.Price,
		arg.PriceFrom,
		arg.PriceTo,
		arg.SharedPackaging,
		arg.Attributes,
		arg.PackageDetails,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateDeleted,
		arg.DateDeletedFrom,
		arg.DateDeletedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductSpu = `-- name: CountProductSpu :one
SELECT COUNT(*)
FROM "catalog"."product_spu"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("number" = ANY($2) OR $2 IS NULL) AND
    ("number" >= $3 OR $3 IS NULL) AND
    ("number" <= $4 OR $4 IS NULL) AND
    ("slug" = ANY($5) OR $5 IS NULL) AND
    ("account_id" = ANY($6) OR $6 IS NULL) AND
    ("category_id" = ANY($7) OR $7 IS NULL) AND
    ("featured_sku_id" = ANY($8) OR $8 IS NULL) AND
    ("name" = ANY($9) OR $9 IS NULL) AND
    ("description" = ANY($10) OR $10 IS NULL) AND
    ("is_enabled" = ANY($11) OR $11 IS NULL) AND
    ("currency" = ANY($12) OR $12 IS NULL) AND
    ("specifications" = ANY($13) OR $13 IS NULL) AND
    ("date_created" = ANY($14) OR $14 IS NULL) AND
    ("date_created" >= $15 OR $15 IS NULL) AND
    ("date_created" <= $16 OR $16 IS NULL) AND
    ("date_updated" = ANY($17) OR $17 IS NULL) AND
    ("date_updated" >= $18 OR $18 IS NULL) AND
    ("date_updated" <= $19 OR $19 IS NULL) AND
    ("date_deleted" = ANY($20) OR $20 IS NULL) AND
    ("date_deleted" >= $21 OR $21 IS NULL) AND
    ("date_deleted" <= $22 OR $22 IS NULL) AND
    ("cached_price" = ANY($23) OR $23 IS NULL) AND
    ("cached_price" >= $24 OR $24 IS NULL) AND
    ("cached_price" <= $25 OR $25 IS NULL) AND
    ("cached_rating" = ANY($26) OR $26 IS NULL) AND
    ("cached_rating" >= $27 OR $27 IS NULL) AND
    ("cached_rating" <= $28 OR $28 IS NULL)
)
`

type CountProductSpuParams struct {
	ID               []uuid.UUID       `db:"id" json:"id"`
	Number           []int64           `db:"number" json:"number"`
	NumberFrom       null.Int          `db:"number_from" json:"number_from"`
	NumberTo         null.Int          `db:"number_to" json:"number_to"`
	Slug             []string          `db:"slug" json:"slug"`
	AccountID        []uuid.UUID       `db:"account_id" json:"account_id"`
	CategoryID       []uuid.UUID       `db:"category_id" json:"category_id"`
	FeaturedSkuID    []uuid.NullUUID   `db:"featured_sku_id" json:"featured_sku_id"`
	Name             []string          `db:"name" json:"name"`
	Description      []string          `db:"description" json:"description"`
	IsEnabled        []bool            `db:"is_enabled" json:"is_enabled"`
	Currency         []string          `db:"currency" json:"currency"`
	Specifications   []json.RawMessage `db:"specifications" json:"specifications"`
	DateCreated      []time.Time       `db:"date_created" json:"date_created"`
	DateCreatedFrom  null.Time         `db:"date_created_from" json:"date_created_from"`
	DateCreatedTo    null.Time         `db:"date_created_to" json:"date_created_to"`
	DateUpdated      []time.Time       `db:"date_updated" json:"date_updated"`
	DateUpdatedFrom  null.Time         `db:"date_updated_from" json:"date_updated_from"`
	DateUpdatedTo    null.Time         `db:"date_updated_to" json:"date_updated_to"`
	DateDeleted      []null.Time       `db:"date_deleted" json:"date_deleted"`
	DateDeletedFrom  null.Time         `db:"date_deleted_from" json:"date_deleted_from"`
	DateDeletedTo    null.Time         `db:"date_deleted_to" json:"date_deleted_to"`
	CachedPrice      []int64           `db:"cached_price" json:"cached_price"`
	CachedPriceFrom  null.Int          `db:"cached_price_from" json:"cached_price_from"`
	CachedPriceTo    null.Int          `db:"cached_price_to" json:"cached_price_to"`
	CachedRating     []float64         `db:"cached_rating" json:"cached_rating"`
	CachedRatingFrom null.Float        `db:"cached_rating_from" json:"cached_rating_from"`
	CachedRatingTo   null.Float        `db:"cached_rating_to" json:"cached_rating_to"`
}

func (q *Queries) CountProductSpu(ctx context.Context, arg CountProductSpuParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductSpu,
		arg.ID,
		arg.Number,
		arg.NumberFrom,
		arg.NumberTo,
		arg.Slug,
		arg.AccountID,
		arg.CategoryID,
		arg.FeaturedSkuID,
		arg.Name,
		arg.Description,
		arg.IsEnabled,
		arg.Currency,
		arg.Specifications,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
		arg.DateDeleted,
		arg.DateDeletedFrom,
		arg.DateDeletedTo,
		arg.CachedPrice,
		arg.CachedPriceFrom,
		arg.CachedPriceTo,
		arg.CachedRating,
		arg.CachedRatingFrom,
		arg.CachedRatingTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductSpuTag = `-- name: CountProductSpuTag :one
SELECT COUNT(*)
FROM "catalog"."product_spu_tag"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("spu_id" = ANY($2) OR $2 IS NULL) AND
    ("tag" = ANY($3) OR $3 IS NULL)
)
`

type CountProductSpuTagParams struct {
	ID    []int64     `db:"id" json:"id"`
	SpuID []uuid.UUID `db:"spu_id" json:"spu_id"`
	Tag   []string    `db:"tag" json:"tag"`
}

func (q *Queries) CountProductSpuTag(ctx context.Context, arg CountProductSpuTagParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductSpuTag, arg.ID, arg.SpuID, arg.Tag)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchSync = `-- name: CountSearchSync :one
SELECT COUNT(*)
FROM "catalog"."search_sync"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("ref_type" = ANY($2) OR $2 IS NULL) AND
    ("ref_id" = ANY($3) OR $3 IS NULL) AND
    ("is_stale_embedding" = ANY($4) OR $4 IS NULL) AND
    ("date_created" = ANY($5) OR $5 IS NULL) AND
    ("date_created" >= $6 OR $6 IS NULL) AND
    ("date_created" <= $7 OR $7 IS NULL) AND
    ("date_updated" = ANY($8) OR $8 IS NULL) AND
    ("date_updated" >= $9 OR $9 IS NULL) AND
    ("date_updated" <= $10 OR $10 IS NULL)
)
`

type CountSearchSyncParams struct {
	ID               []int64                    `db:"id" json:"id"`
	RefType          []CatalogSearchSyncRefType `db:"ref_type" json:"ref_type"`
	RefID            []uuid.UUID                `db:"ref_id" json:"ref_id"`
	IsStaleEmbedding []bool                     `db:"is_stale_embedding" json:"is_stale_embedding"`
	DateCreated      []time.Time                `db:"date_created" json:"date_created"`
	DateCreatedFrom  null.Time                  `db:"date_created_from" json:"date_created_from"`
	DateCreatedTo    null.Time                  `db:"date_created_to" json:"date_created_to"`
	DateUpdated      []time.Time                `db:"date_updated" json:"date_updated"`
	DateUpdatedFrom  null.Time                  `db:"date_updated_from" json:"date_updated_from"`
	DateUpdatedTo    null.Time                  `db:"date_updated_to" json:"date_updated_to"`
}

func (q *Queries) CountSearchSync(ctx context.Context, arg CountSearchSyncParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchSync,
		arg.ID,
		arg.RefType,
		arg.RefID,
		arg.IsStaleEmbedding,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTag = `-- name: CountTag :one
SELECT COUNT(*)
FROM "catalog"."tag"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("name" = ANY($2) OR $2 IS NULL) AND
    ("description" = ANY($3) OR $3 IS NULL)
)
`

type CountTagParams struct {
	ID          []string      `db:"id" json:"id"`
	Name        []string      `db:"name" json:"name"`
	Description []null.String `db:"description" json:"description"`
}

func (q *Queries) CountTag(ctx context.Context, arg CountTagParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTag, arg.ID, arg.Name, arg.Description)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO "catalog"."category" ("id", "name", "description", "parent_id")
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, parent_id
`

type CreateCategoryParams struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	Name        string        `db:"name" json:"name"`
	Description string        `db:"description" json:"description"`
	ParentID    uuid.NullUUID `db:"parent_id" json:"parent_id"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ParentID,
	)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO "catalog"."comment" ("id", "account_id", "order_id", "ref_type", "ref_id", "body", "upvote", "downvote", "score", "date_created", "date_updated")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, account_id, order_id, ref_type, ref_id, body, upvote, downvote, score, date_created, date_updated
`

type CreateCommentParams struct {
	ID          uuid.UUID             `db:"id" json:"id"`
	AccountID   uuid.UUID             `db:"account_id" json:"account_id"`
	OrderID     uuid.NullUUID         `db:"order_id" json:"order_id"`
	RefType     CatalogCommentRefType `db:"ref_type" json:"ref_type"`
	RefID       uuid.UUID             `db:"ref_id" json:"ref_id"`
	Body        string                `db:"body" json:"body"`
	Upvote      int64                 `db:"upvote" json:"upvote"`
	Downvote    int64                 `db:"downvote" json:"downvote"`
	Score       float64               `db:"score" json:"score"`
	DateCreated time.Time             `db:"date_created" json:"date_created"`
	DateUpdated time.Time             `db:"date_updated" json:"date_updated"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CatalogComment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.AccountID,
		arg.OrderID,
		arg.RefType,
		arg.RefID,
		arg.Body,
		arg.Upvote,
		arg.Downvote,
		arg.Score,
		arg.DateCreated,
		arg.DateUpdated,
	)
	var i CatalogComment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OrderID,
		&i.RefType,
		&i.RefID,
		&i.Body,
		&i.Upvote,
		&i.Downvote,
		&i.Score,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

type CreateCopyCategoryParams struct {
	ID          uuid.UUID     `db:"id" json:"id"`
	Name        string        `db:"name" json:"name"`
	Description string        `db:"description" json:"description"`
	ParentID    uuid.NullUUID `db:"parent_id" json:"parent_id"`
}

type CreateCopyCommentParams struct {
	ID          uuid.UUID             `db:"id" json:"id"`
	AccountID   uuid.UUID             `db:"account_id" json:"account_id"`
	OrderID     uuid.NullUUID         `db:"order_id" json:"order_id"`
	RefType     CatalogCommentRefType `db:"ref_type" json:"ref_type"`
	RefID       uuid.UUID             `db:"ref_id" json:"ref_id"`
	Body        string                `db:"body" json:"body"`
	Upvote      int64                 `db:"upvote" json:"upvote"`
	Downvote    int64                 `db:"downvote" json:"downvote"`
	Score       float64               `db:"score" json:"score"`
	DateCreated time.Time             `db:"date_created" json:"date_created"`
	DateUpdated time.Time             `db:"date_updated" json:"date_updated"`
}

type CreateCopyDefaultCategoryParams struct {
	Name        string        `db:"name" json:"name"`
	Description string        `db:"description" json:"description"`
	ParentID    uuid.NullUUID `db:"parent_id" json:"parent_id"`
}

type CreateCopyDefaultCommentParams struct {
	AccountID uuid.UUID             `db:"account_id" json:"account_id"`
	OrderID   uuid.NullUUID         `db:"order_id" json:"order_id"`
	RefType   CatalogCommentRefType `db:"ref_type" json:"ref_type"`
	RefID     uuid.UUID             `db:"ref_id" json:"ref_id"`
	Body      string                `db:"body" json:"body"`
	Score     float64               `db:"score" json:"score"`
}

type CreateCopyDefaultProductSkuParams struct {
	SpuID           uuid.UUID       `db:"spu_id" json:"spu_id"`
	Price           int64           `db:"price" json:"price"`
	SharedPackaging bool            `db:"shared_packaging" json:"shared_packaging"`
	Attributes      json.RawMessage `db:"attributes" json:"attributes"`
	PackageDetails  json.RawMessage `db:"package_details" json:"package_details"`
	DateDeleted     null.Time       `db:"date_deleted" json:"date_deleted"`
}

type CreateCopyDefaultProductSpuParams struct {
	Slug           string          `db:"slug" json:"slug"`
	AccountID      uuid.UUID       `db:"account_id" json:"account_id"`
	CategoryID     uuid.UUID       `db:"category_id" json:"category_id"`
	FeaturedSkuID  uuid.NullUUID   `db:"featured_sku_id" json:"featured_sku_id"`
	Name           string          `db:"name" json:"name"`
	Description    string          `db:"description" json:"description"`
	IsEnabled      bool            `db:"is_enabled" json:"is_enabled"`
	Currency       string          `db:"currency" json:"currency"`
	Specifications json.RawMessage `db:"specifications" json:"specifications"`
	DateDeleted    null.Time       `db:"date_deleted" json:"date_deleted"`
}

type CreateCopyDefaultProductSpuTagParams struct {
	SpuID uuid.UUID `db:"spu_id" json:"spu_id"`
	Tag   string    `db:"tag" json:"tag"`
}

type CreateCopyDefaultSearchSyncParams struct {
	RefType CatalogSearchSyncRefType `db:"ref_type" json:"ref_type"`
	RefID   uuid.UUID                `db:"ref_id" json:"ref_id"`
}

type CreateCopyDefaultTagParams struct {
	ID          string      `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description null.String `db:"description" json:"description"`
}

type CreateCopyProductSkuParams struct {
	ID              uuid.UUID       `db:"id" json:"id"`
	SpuID           uuid.UUID       `db:"spu_id" json:"spu_id"`
	Price           int64           `db:"price" json:"price"`
	SharedPackaging bool            `db:"shared_packaging" json:"shared_packaging"`
	Attributes      json.RawMessage `db:"attributes" json:"attributes"`
	PackageDetails  json.RawMessage `db:"package_details" json:"package_details"`
	DateCreated     time.Time       `db:"date_created" json:"date_created"`
	DateDeleted     null.Time       `db:"date_deleted" json:"date_deleted"`
}

type CreateCopyProductSpuParams struct {
	ID             uuid.UUID       `db:"id" json:"id"`
	Slug           string          `db:"slug" json:"slug"`
	AccountID      uuid.UUID       `db:"account_id" json:"account_id"`
	CategoryID     uuid.UUID       `db:"category_id" json:"category_id"`
	FeaturedSkuID  uuid.NullUUID   `db:"featured_sku_id" json:"featured_sku_id"`
	Name           string          `db:"name" json:"name"`
	Description    string          `db:"description" json:"description"`
	IsEnabled      bool            `db:"is_enabled" json:"is_enabled"`
	Currency       string          `db:"currency" json:"currency"`
	Specifications json.RawMessage `db:"specifications" json:"specifications"`
	DateCreated    time.Time       `db:"date_created" json:"date_created"`
	DateUpdated    time.Time       `db:"date_updated" json:"date_updated"`
	DateDeleted    null.Time       `db:"date_deleted" json:"date_deleted"`
	CachedPrice    int64           `db:"cached_price" json:"cached_price"`
	CachedRating   float64         `db:"cached_rating" json:"cached_rating"`
}

type CreateCopyProductSpuTagParams struct {
	SpuID uuid.UUID `db:"spu_id" json:"spu_id"`
	Tag   string    `db:"tag" json:"tag"`
}

type CreateCopySearchSyncParams struct {
	RefType          CatalogSearchSyncRefType `db:"ref_type" json:"ref_type"`
	RefID            uuid.UUID                `db:"ref_id" json:"ref_id"`
	IsStaleEmbedding bool                     `db:"is_stale_embedding" json:"is_stale_embedding"`
	DateCreated      time.Time                `db:"date_created" json:"date_created"`
	DateUpdated      time.Time                `db:"date_updated" json:"date_updated"`
}

type CreateCopyTagParams struct {
	ID          string      `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description null.String `db:"description" json:"description"`
}

const createDefaultCategory = `-- name: CreateDefaultCategory :one
INSERT INTO "catalog"."category" ("name", "description", "parent_id")
VALUES ($1, $2, $3)
RETURNING id, name, description, parent_id
`

type CreateDefaultCategoryParams struct {
	Name        string        `db:"name" json:"name"`
	Description string        `db:"description" json:"description"`
	ParentID    uuid.NullUUID `db:"parent_id" json:"parent_id"`
}

func (q *Queries) CreateDefaultCategory(ctx context.Context, arg CreateDefaultCategoryParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, createDefaultCategory, arg.Name, arg.Description, arg.ParentID)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
	)
	return i, err
}

const createDefaultComment = `-- name: CreateDefaultComment :one
INSERT INTO "catalog"."comment" ("account_id", "order_id", "ref_type", "ref_id", "body", "score")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, order_id, ref_type, ref_id, body, upvote, downvote, score, date_created, date_updated
`

type CreateDefaultCommentParams struct {
	AccountID uuid.UUID             `db:"account_id" json:"account_id"`
	OrderID   uuid.NullUUID         `db:"order_id" json:"order_id"`
	RefType   CatalogCommentRefType `db:"ref_type" json:"ref_type"`
	RefID     uuid.UUID             `db:"ref_id" json:"ref_id"`
	Body      string                `db:"body" json:"body"`
	Score     float64               `db:"score" json:"score"`
}

func (q *Queries) CreateDefaultComment(ctx context.Context, arg CreateDefaultCommentParams) (CatalogComment, error) {
	row := q.db.QueryRow(ctx, createDefaultComment,
		arg.AccountID,
		arg.OrderID,
		arg.RefType,
		arg.RefID,
		arg.Body,
		arg.Score,
	)
	var i CatalogComment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OrderID,
		&i.RefType,
		&i.RefID,
		&i.Body,
		&i.Upvote,
		&i.Downvote,
		&i.Score,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const createDefaultProductSku = `-- name: CreateDefaultProductSku :one
INSERT INTO "catalog"."product_sku" ("spu_id", "price", "shared_packaging", "attributes", "package_details", "date_deleted")
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, spu_id, price, shared_packaging, attributes, package_details, date_created, date_deleted
`

type CreateDefaultProductSkuParams struct {
	SpuID           uuid.UUID       `db:"spu_id" json:"spu_id"`
	Price           int64           `db:"price" json:"price"`
	SharedPackaging bool            `db:"shared_packaging" json:"shared_packaging"`
	Attributes      json.RawMessage `db:"attributes" json:"attributes"`
	PackageDetails  json.RawMessage `db:"package_details" json:"package_details"`
	DateDeleted     null.Time       `db:"date_deleted" json:"date_deleted"`
}

func (q *Queries) CreateDefaultProductSku(ctx context.Context, arg CreateDefaultProductSkuParams) (CatalogProductSku, error) {
	row := q.db.QueryRow(ctx, createDefaultProductSku,
		arg.SpuID,
		arg.Price,
		arg.SharedPackaging,
		arg.Attributes,
		arg.PackageDetails,
		arg.DateDeleted,
	)
	var i CatalogProductSku
	err := row.Scan(
		&i.ID,
		&i.SpuID,
		&i.Price,
		&i.SharedPackaging,
		&i.Attributes,
		&i.PackageDetails,
		&i.DateCreated,
		&i.DateDeleted,
	)
	return i, err
}

const createDefaultProductSpu = `-- name: CreateDefaultProductSpu :one
INSERT INTO "catalog"."product_spu" ("slug", "account_id", "category_id", "featured_sku_id", "name", "description", "is_enabled", "currency", "specifications", "date_deleted")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, number, slug, account_id, category_id, featured_sku_id, name, description, is_enabled, currency, specifications, date_created, date_updated, date_deleted, cached_price, cached_rating
`

type CreateDefaultProductSpuParams struct {
	Slug           string          `db:"slug" json:"slug"`
	AccountID      uuid.UUID       `db:"account_id" json:"account_id"`
	CategoryID     uuid.UUID       `db:"category_id" json:"category_id"`
	FeaturedSkuID  uuid.NullUUID   `db:"featured_sku_id" json:"featured_sku_id"`
	Name           string          `db:"name" json:"name"`
	Description    string          `db:"description" json:"description"`
	IsEnabled      bool            `db:"is_enabled" json:"is_enabled"`
	Currency       string          `db:"currency" json:"currency"`
	Specifications json.RawMessage `db:"specifications" json:"specifications"`
	DateDeleted    null.Time       `db:"date_deleted" json:"date_deleted"`
}

func (q *Queries) CreateDefaultProductSpu(ctx context.Context, arg CreateDefaultProductSpuParams) (CatalogProductSpu, error) {
	row := q.db.QueryRow(ctx, createDefaultProductSpu,
		arg.Slug,
		arg.AccountID,
		arg.CategoryID,
		arg.FeaturedSkuID,
		arg.Name,
		arg.Description,
		arg.IsEnabled,
		arg.Currency,
		arg.Specifications,
		arg.DateDeleted,
	)
	var i CatalogProductSpu
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Slug,
		&i.AccountID,
		&i.CategoryID,
		&i.FeaturedSkuID,
		&i.Name,
		&i.Description,
		&i.IsEnabled,
		&i.Currency,
		&i.Specifications,
		&i.DateCreated,
		&i.DateUpdated,
		&i.DateDeleted,
		&i.CachedPrice,
		&i.CachedRating,
	)
	return i, err
}

const createDefaultProductSpuTag = `-- name: CreateDefaultProductSpuTag :one
INSERT INTO "catalog"."product_spu_tag" ("spu_id", "tag")
VALUES ($1, $2)
RETURNING id, spu_id, tag
`

type CreateDefaultProductSpuTagParams struct {
	SpuID uuid.UUID `db:"spu_id" json:"spu_id"`
	Tag   string    `db:"tag" json:"tag"`
}

func (q *Queries) CreateDefaultProductSpuTag(ctx context.Context, arg CreateDefaultProductSpuTagParams) (CatalogProductSpuTag, error) {
	row := q.db.QueryRow(ctx, createDefaultProductSpuTag, arg.SpuID, arg.Tag)
	var i CatalogProductSpuTag
	err := row.Scan(&i.ID, &i.SpuID, &i.Tag)
	return i, err
}

const createDefaultSearchSync = `-- name: CreateDefaultSearchSync :one
INSERT INTO "catalog"."search_sync" ("ref_type", "ref_id")
VALUES ($1, $2)
RETURNING id, ref_type, ref_id, is_stale_embedding, date_created, date_updated
`

type CreateDefaultSearchSyncParams struct {
	RefType CatalogSearchSyncRefType `db:"ref_type" json:"ref_type"`
	RefID   uuid.UUID                `db:"ref_id" json:"ref_id"`
}

func (q *Queries) CreateDefaultSearchSync(ctx context.Context, arg CreateDefaultSearchSyncParams) (CatalogSearchSync, error) {
	row := q.db.QueryRow(ctx, createDefaultSearchSync, arg.RefType, arg.RefID)
	var i CatalogSearchSync
	err := row.Scan(
		&i.ID,
		&i.RefType,
		&i.RefID,
		&i.IsStaleEmbedding,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const createDefaultTag = `-- name: CreateDefaultTag :one
INSERT INTO "catalog"."tag" ("id", "name", "description")
VALUES ($1, $2, $3)
RETURNING id, name, description
`

type CreateDefaultTagParams struct {
	ID          string      `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description null.String `db:"description" json:"description"`
}

func (q *Queries) CreateDefaultTag(ctx context.Context, arg CreateDefaultTagParams) (CatalogTag, error) {
	row := q.db.QueryRow(ctx, createDefaultTag, arg.ID, arg.Name, arg.Description)
	var i CatalogTag
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const createProductSku = `-- name: CreateProductSku :one
INSERT INTO "catalog"."product_sku" ("id", "spu_id", "price", "shared_packaging", "attributes", "package_details", "date_created", "date_deleted")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, spu_id, price, shared_packaging, attributes, package_details, date_created, date_deleted
`

type CreateProductSkuParams struct {
	ID              uuid.UUID       `db:"id" json:"id"`
	SpuID           uuid.UUID       `db:"spu_id" json:"spu_id"`
	Price           int64           `db:"price" json:"price"`
	SharedPackaging bool            `db:"shared_packaging" json:"shared_packaging"`
	Attributes      json.RawMessage `db:"attributes" json:"attributes"`
	PackageDetails  json.RawMessage `db:"package_details" json:"package_details"`
	DateCreated     time.Time       `db:"date_created" json:"date_created"`
	DateDeleted     null.Time       `db:"date_deleted" json:"date_deleted"`
}

func (q *Queries) CreateProductSku(ctx context.Context, arg CreateProductSkuParams) (CatalogProductSku, error) {
	row := q.db.QueryRow(ctx, createProductSku,
		arg.ID,
		arg.SpuID,
		arg.Price,
		arg.SharedPackaging,
		arg.Attributes,
		arg.PackageDetails,
		arg.DateCreated,
		arg.DateDeleted,
	)
	var i CatalogProductSku
	err := row.Scan(
		&i.ID,
		&i.SpuID,
		&i.Price,
		&i.SharedPackaging,
		&i.Attributes,
		&i.PackageDetails,
		&i.DateCreated,
		&i.DateDeleted,
	)
	return i, err
}

const createProductSpu = `-- name: CreateProductSpu :one
INSERT INTO "catalog"."product_spu" ("id", "slug", "account_id", "category_id", "featured_sku_id", "name", "description", "is_enabled", "currency", "specifications", "date_created", "date_updated", "date_deleted", "cached_price", "cached_rating")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, number, slug, account_id, category_id, featured_sku_id, name, description, is_enabled, currency, specifications, date_created, date_updated, date_deleted, cached_price, cached_rating
`

type CreateProductSpuParams struct {
	ID             uuid.UUID       `db:"id" json:"id"`
	Slug           string          `db:"slug" json:"slug"`
	AccountID      uuid.UUID       `db:"account_id" json:"account_id"`
	CategoryID     uuid.UUID       `db:"category_id" json:"category_id"`
	FeaturedSkuID  uuid.NullUUID   `db:"featured_sku_id" json:"featured_sku_id"`
	Name           string          `db:"name" json:"name"`
	Description    string          `db:"description" json:"description"`
	IsEnabled      bool            `db:"is_enabled" json:"is_enabled"`
	Currency       string          `db:"currency" json:"currency"`
	Specifications json.RawMessage `db:"specifications" json:"specifications"`
	DateCreated    time.Time       `db:"date_created" json:"date_created"`
	DateUpdated    time.Time       `db:"date_updated" json:"date_updated"`
	DateDeleted    null.Time       `db:"date_deleted" json:"date_deleted"`
	CachedPrice    int64           `db:"cached_price" json:"cached_price"`
	CachedRating   float64         `db:"cached_rating" json:"cached_rating"`
}

func (q *Queries) CreateProductSpu(ctx context.Context, arg CreateProductSpuParams) (CatalogProductSpu, error) {
	row := q.db.QueryRow(ctx, createProductSpu,
		arg.ID,
		arg.Slug,
		arg.AccountID,
		arg.CategoryID,
		arg.FeaturedSkuID,
		arg.Name,
		arg.Description,
		arg.IsEnabled,
		arg.Currency,
		arg.Specifications,
		arg.DateCreated,
		arg.DateUpdated,
		arg.DateDeleted,
		arg.CachedPrice,
		arg.CachedRating,
	)
	var i CatalogProductSpu
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Slug,
		&i.AccountID,
		&i.CategoryID,
		&i.FeaturedSkuID,
		&i.Name,
		&i.Description,
		&i.IsEnabled,
		&i.Currency,
		&i.Specifications,
		&i.DateCreated,
		&i.DateUpdated,
		&i.DateDeleted,
		&i.CachedPrice,
		&i.CachedRating,
	)
	return i, err
}

const createProductSpuTag = `-- name: CreateProductSpuTag :one
INSERT INTO "catalog"."product_spu_tag" ("spu_id", "tag")
VALUES ($1, $2)
RETURNING id, spu_id, tag
`

type CreateProductSpuTagParams struct {
	SpuID uuid.UUID `db:"spu_id" json:"spu_id"`
	Tag   string    `db:"tag" json:"tag"`
}

func (q *Queries) CreateProductSpuTag(ctx context.Context, arg CreateProductSpuTagParams) (CatalogProductSpuTag, error) {
	row := q.db.QueryRow(ctx, createProductSpuTag, arg.SpuID, arg.Tag)
	var i CatalogProductSpuTag
	err := row.Scan(&i.ID, &i.SpuID, &i.Tag)
	return i, err
}

const createSearchSync = `-- name: CreateSearchSync :one
INSERT INTO "catalog"."search_sync" ("ref_type", "ref_id", "is_stale_embedding", "date_created", "date_updated")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ref_type, ref_id, is_stale_embedding, date_created, date_updated
`

type CreateSearchSyncParams struct {
	RefType          CatalogSearchSyncRefType `db:"ref_type" json:"ref_type"`
	RefID            uuid.UUID                `db:"ref_id" json:"ref_id"`
	IsStaleEmbedding bool                     `db:"is_stale_embedding" json:"is_stale_embedding"`
	DateCreated      time.Time                `db:"date_created" json:"date_created"`
	DateUpdated      time.Time                `db:"date_updated" json:"date_updated"`
}

func (q *Queries) CreateSearchSync(ctx context.Context, arg CreateSearchSyncParams) (CatalogSearchSync, error) {
	row := q.db.QueryRow(ctx, createSearchSync,
		arg.RefType,
		arg.RefID,
		arg.IsStaleEmbedding,
		arg.DateCreated,
		arg.DateUpdated,
	)
	var i CatalogSearchSync
	err := row.Scan(
		&i.ID,
		&i.RefType,
		&i.RefID,
		&i.IsStaleEmbedding,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO "catalog"."tag" ("id", "name", "description")
VALUES ($1, $2, $3)
RETURNING id, name, description
`

type CreateTagParams struct {
	ID          string      `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description null.String `db:"description" json:"description"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (CatalogTag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.ID, arg.Name, arg.Description)
	var i CatalogTag
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM "catalog"."category"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("name" = ANY($2) OR $2 IS NULL) AND
    ("description" = ANY($3) OR $3 IS NULL) AND
    ("parent_id" = ANY($4) OR $4 IS NULL)
)
`

type DeleteCategoryParams struct {
	ID          []uuid.UUID     `db:"id" json:"id"`
	Name        []string        `db:"name" json:"name"`
	Description []string        `db:"description" json:"description"`
	ParentID    []uuid.NullUUID `db:"parent_id" json:"parent_id"`
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ParentID,
	)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM "catalog"."comment"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("account_id" = ANY($2) OR $2 IS NULL) AND
    ("order_id" = ANY($3) OR $3 IS NULL) AND
    ("ref_type" = ANY($4) OR $4 IS NULL) AND
    ("ref_id" = ANY($5) OR $5 IS NULL) AND
    ("body" = ANY($6) OR $6 IS NULL) AND
    ("upvote" = ANY($7) OR $7 IS NULL) AND
    ("upvote" >= $8 OR $8 IS NULL) AND
    ("upvote" <= $9 OR $9 IS NULL) AND
    ("downvote" = ANY($10) OR $10 IS NULL) AND
    ("downvote" >= $11 OR $11 IS NULL) AND
    ("downvote" <= $12 OR $12 IS NULL) AND
    ("score" = ANY($13) OR $13 IS NULL) AND
    ("score" >= $14 OR $14 IS NULL) AND
    ("score" <= $15 OR $15 IS NULL) AND
    ("date_created" = ANY($16) OR $16 IS NULL) AND
    ("date_created" >= $17 OR $17 IS NULL) AND
    ("date_created" <= $18 OR $18 IS NULL) AND
    ("date_updated" = ANY($19) OR $19 IS NULL) AND
    ("date_updated" >= $20 OR $20 IS NULL) AND
    ("date_updated" <= $21 OR $21 IS NULL)
)
`

type DeleteCommentParams struct {
	ID              []uuid.UUID             `db:"id" json:"id"`
	AccountID       []uuid.UUID             `db:"account_id" json:"account_id"`
	OrderID         []uuid.NullUUID         `db:"order_id" json:"order_id"`
	RefType         []CatalogCommentRefType `db:"ref_type" json:"ref_type"`
	RefID           []uuid.UUID             `db:"ref_id" json:"ref_id"`
	Body            []string                `db:"body" json:"body"`
	Upvote          []int64                 `db:"upvote" json:"upvote"`
	UpvoteFrom      null.Int                `db:"upvote_from" json:"upvote_from"`
	UpvoteTo        null.Int                `db:"upvote_to" json:"upvote_to"`
	Downvote        []int64                 `db:"downvote" json:"downvote"`
	DownvoteFrom    null.Int                `db:"downvote_from" json:"downvote_from"`
	DownvoteTo      null.Int                `db:"downvote_to" json:"downvote_to"`
	Score           []float64               `db:"score" json:"score"`
	ScoreFrom       null.Float              `db:"score_from" json:"score_from"`
	ScoreTo         null.Float              `db:"score_to" json:"score_to"`
	DateCreated     []time.Time             `db:"date_created" json:"date_created"`
	DateCreatedFrom null.Time               `db:"date_created_from" json:"date_created_from"`
	DateCreatedTo   null.Time               `db:"date_created_to" json:"date_created_to"`
	DateUpdated     []time.Time             `db:"date_updated" json:"date_updated"`
	DateUpdatedFrom null.Time               `db:"date_updated_from" json:"date_updated_from"`
	DateUpdatedTo   null.Time               `db:"date_updated_to" json:"date_updated_to"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.Exec(ctx, deleteComment,
		arg.ID,
		arg.AccountID,
		arg.OrderID,
		arg.RefType,
		arg.RefID,
		arg.Body,
		arg.Upvote,
		arg.UpvoteFrom,
		arg.UpvoteTo,
		arg.Downvote,
		arg.DownvoteFrom,
		arg.DownvoteTo,
		arg.Score,
		arg.ScoreFrom,
		arg.ScoreTo,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
	)
	return err
}

const deleteProductSku = `-- name: DeleteProductSku :exec
DELETE FROM "catalog"."product_sku"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("spu_id" = ANY($2) OR $2 IS NULL) AND
    ("price" = ANY($3) OR $3 IS NULL) AND
    ("price" >= $4 OR $4 IS NULL) AND
    ("price" <= $5 OR $5 IS NULL) AND
    ("shared_packaging" = ANY($6) OR $6 IS NULL) AND
    ("attributes" = ANY($7) OR $7 IS NULL) AND
    ("package_details" = ANY($8) OR $8 IS NULL) AND
    ("date_created" = ANY($9) OR $9 IS NULL) AND
    ("date_created" >= $10 OR $10 IS NULL) AND
    ("date_created" <= $11 OR $11 IS NULL) AND
    ("date_deleted" = ANY($12) OR $12 IS NULL) AND
    ("date_deleted" >= $13 OR $13 IS NULL) AND
    ("date_deleted" <= $14 OR $14 IS NULL)
)
`

type DeleteProductSkuParams struct {
	ID              []uuid.UUID       `db:"id" json:"id"`
	SpuID           []uuid.UUID       `db:"spu_id" json:"spu_id"`
	Price           []int64           `db:"price" json:"price"`
	PriceFrom       null.Int          `db:"price_from" json:"price_from"`
	PriceTo         null.Int          `db:"price_to" json:"price_to"`
	SharedPackaging []bool            `db:"shared_packaging" json:"shared_packaging"`
	Attributes      []json.RawMessage `db:"attributes" json:"attributes"`
	PackageDetails  []json.RawMessage `db:"package_details" json:"package_details"`
	DateCreated     []time.Time       `db:"date_created" json:"date_created"`
	DateCreatedFrom null.Time         `db:"date_created_from" json:"date_created_from"`
	DateCreatedTo   null.Time         `db:"date_created_to" json:"date_created_to"`
	DateDeleted     []null.Time       `db:"date_deleted" json:"date_deleted"`
	DateDeletedFrom null.Time         `db:"date_deleted_from" json:"date_deleted_from"`
	DateDeletedTo   null.Time         `db:"date_deleted_to" json:"date_deleted_to"`
}

func (q *Queries) DeleteProductSku(ctx context.Context, arg DeleteProductSkuParams) error {
	_, err := q.db.Exec(ctx, deleteProductSku,
		arg.ID,
		arg.SpuID,
		arg.Price,
		arg.PriceFrom,
		arg.PriceTo,
		arg.SharedPackaging,
		arg.Attributes,
		arg.PackageDetails,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateDeleted,
		arg.DateDeletedFrom,
		arg.DateDeletedTo,
	)
	return err
}

const deleteProductSpu = `-- name: DeleteProductSpu :exec
DELETE FROM "catalog"."product_spu"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("number" = ANY($2) OR $2 IS NULL) AND
    ("number" >= $3 OR $3 IS NULL) AND
    ("number" <= $4 OR $4 IS NULL) AND
    ("slug" = ANY($5) OR $5 IS NULL) AND
    ("account_id" = ANY($6) OR $6 IS NULL) AND
    ("category_id" = ANY($7) OR $7 IS NULL) AND
    ("featured_sku_id" = ANY($8) OR $8 IS NULL) AND
    ("name" = ANY($9) OR $9 IS NULL) AND
    ("description" = ANY($10) OR $10 IS NULL) AND
    ("is_enabled" = ANY($11) OR $11 IS NULL) AND
    ("currency" = ANY($12) OR $12 IS NULL) AND
    ("specifications" = ANY($13) OR $13 IS NULL) AND
    ("date_created" = ANY($14) OR $14 IS NULL) AND
    ("date_created" >= $15 OR $15 IS NULL) AND
    ("date_created" <= $16 OR $16 IS NULL) AND
    ("date_updated" = ANY($17) OR $17 IS NULL) AND
    ("date_updated" >= $18 OR $18 IS NULL) AND
    ("date_updated" <= $19 OR $19 IS NULL) AND
    ("date_deleted" = ANY($20) OR $20 IS NULL) AND
    ("date_deleted" >= $21 OR $21 IS NULL) AND
    ("date_deleted" <= $22 OR $22 IS NULL) AND
    ("cached_price" = ANY($23) OR $23 IS NULL) AND
    ("cached_price" >= $24 OR $24 IS NULL) AND
    ("cached_price" <= $25 OR $25 IS NULL) AND
    ("cached_rating" = ANY($26) OR $26 IS NULL) AND
    ("cached_rating" >= $27 OR $27 IS NULL) AND
    ("cached_rating" <= $28 OR $28 IS NULL)
)
`

type DeleteProductSpuParams struct {
	ID               []uuid.UUID       `db:"id" json:"id"`
	Number           []int64           `db:"number" json:"number"`
	NumberFrom       null.Int          `db:"number_from" json:"number_from"`
	NumberTo         null.Int          `db:"number_to" json:"number_to"`
	Slug             []string          `db:"slug" json:"slug"`
	AccountID        []uuid.UUID       `db:"account_id" json:"account_id"`
	CategoryID       []uuid.UUID       `db:"category_id" json:"category_id"`
	FeaturedSkuID    []uuid.NullUUID   `db:"featured_sku_id" json:"featured_sku_id"`
	Name             []string          `db:"name" json:"name"`
	Description      []string          `db:"description" json:"description"`
	IsEnabled        []bool            `db:"is_enabled" json:"is_enabled"`
	Currency         []string          `db:"currency" json:"currency"`
	Specifications   []json.RawMessage `db:"specifications" json:"specifications"`
	DateCreated      []time.Time       `db:"date_created" json:"date_created"`
	DateCreatedFrom  null.Time         `db:"date_created_from" json:"date_created_from"`
	DateCreatedTo    null.Time         `db:"date_created_to" json:"date_created_to"`
	DateUpdated      []time.Time       `db:"date_updated" json:"date_updated"`
	DateUpdatedFrom  null.Time         `db:"date_updated_from" json:"date_updated_from"`
	DateUpdatedTo    null.Time         `db:"date_updated_to" json:"date_updated_to"`
	DateDeleted      []null.Time       `db:"date_deleted" json:"date_deleted"`
	DateDeletedFrom  null.Time         `db:"date_deleted_from" json:"date_deleted_from"`
	DateDeletedTo    null.Time         `db:"date_deleted_to" json:"date_deleted_to"`
	CachedPrice      []int64           `db:"cached_price" json:"cached_price"`
	CachedPriceFrom  null.Int          `db:"cached_price_from" json:"cached_price_from"`
	CachedPriceTo    null.Int          `db:"cached_price_to" json:"cached_price_to"`
	CachedRating     []float64         `db:"cached_rating" json:"cached_rating"`
	CachedRatingFrom null.Float        `db:"cached_rating_from" json:"cached_rating_from"`
	CachedRatingTo   null.Float        `db:"cached_rating_to" json:"cached_rating_to"`
}

func (q *Queries) DeleteProductSpu(ctx context.Context, arg DeleteProductSpuParams) error {
	_, err := q.db.Exec(ctx, deleteProductSpu,
		arg.ID,
		arg.Number,
		arg.NumberFrom,
		arg.NumberTo,
		arg.Slug,
		arg.AccountID,
		arg.CategoryID,
		arg.FeaturedSkuID,
		arg.Name,
		arg.Description,
		arg.IsEnabled,
		arg.Currency,
		arg.Specifications,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
		arg.DateDeleted,
		arg.DateDeletedFrom,
		arg.DateDeletedTo,
		arg.CachedPrice,
		arg.CachedPriceFrom,
		arg.CachedPriceTo,
		arg.CachedRating,
		arg.CachedRatingFrom,
		arg.CachedRatingTo,
	)
	return err
}

const deleteProductSpuTag = `-- name: DeleteProductSpuTag :exec
DELETE FROM "catalog"."product_spu_tag"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("spu_id" = ANY($2) OR $2 IS NULL) AND
    ("tag" = ANY($3) OR $3 IS NULL)
)
`

type DeleteProductSpuTagParams struct {
	ID    []int64     `db:"id" json:"id"`
	SpuID []uuid.UUID `db:"spu_id" json:"spu_id"`
	Tag   []string    `db:"tag" json:"tag"`
}

func (q *Queries) DeleteProductSpuTag(ctx context.Context, arg DeleteProductSpuTagParams) error {
	_, err := q.db.Exec(ctx, deleteProductSpuTag, arg.ID, arg.SpuID, arg.Tag)
	return err
}

const deleteSearchSync = `-- name: DeleteSearchSync :exec
DELETE FROM "catalog"."search_sync"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("ref_type" = ANY($2) OR $2 IS NULL) AND
    ("ref_id" = ANY($3) OR $3 IS NULL) AND
    ("is_stale_embedding" = ANY($4) OR $4 IS NULL) AND
    ("date_created" = ANY($5) OR $5 IS NULL) AND
    ("date_created" >= $6 OR $6 IS NULL) AND
    ("date_created" <= $7 OR $7 IS NULL) AND
    ("date_updated" = ANY($8) OR $8 IS NULL) AND
    ("date_updated" >= $9 OR $9 IS NULL) AND
    ("date_updated" <= $10 OR $10 IS NULL)
)
`

type DeleteSearchSyncParams struct {
	ID               []int64                    `db:"id" json:"id"`
	RefType          []CatalogSearchSyncRefType `db:"ref_type" json:"ref_type"`
	RefID            []uuid.UUID                `db:"ref_id" json:"ref_id"`
	IsStaleEmbedding []bool                     `db:"is_stale_embedding" json:"is_stale_embedding"`
	DateCreated      []time.Time                `db:"date_created" json:"date_created"`
	DateCreatedFrom  null.Time                  `db:"date_created_from" json:"date_created_from"`
	DateCreatedTo    null.Time                  `db:"date_created_to" json:"date_created_to"`
	DateUpdated      []time.Time                `db:"date_updated" json:"date_updated"`
	DateUpdatedFrom  null.Time                  `db:"date_updated_from" json:"date_updated_from"`
	DateUpdatedTo    null.Time                  `db:"date_updated_to" json:"date_updated_to"`
}

func (q *Queries) DeleteSearchSync(ctx context.Context, arg DeleteSearchSyncParams) error {
	_, err := q.db.Exec(ctx, deleteSearchSync,
		arg.ID,
		arg.RefType,
		arg.RefID,
		arg.IsStaleEmbedding,
		arg.DateCreated,
		arg.DateCreatedFrom,
		arg.DateCreatedTo,
		arg.DateUpdated,
		arg.DateUpdatedFrom,
		arg.DateUpdatedTo,
	)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM "catalog"."tag"
WHERE (
    ("id" = ANY($1) OR $1 IS NULL) AND
    ("name" = ANY($2) OR $2 IS NULL) AND
    ("description" = ANY($3) OR $3 IS NULL)
)
`

type DeleteTagParams struct {
	ID          []string      `db:"id" json:"id"`
	Name        []string      `db:"name" json:"name"`
	Description []null.String `db:"description" json:"description"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.Name, arg.Description)
	return err
}

const getCategory = `-- name: GetCategory :one



SELECT id, name, description, parent_id
FROM "catalog"."category"
WHERE ("id" = $1) OR ("name" = $2)
`

type GetCategoryParams struct {
	ID   uuid.NullUUID `db:"id" json:"id"`
	Name null.String   `db:"name" json:"name"`
}

// Code generated by pgtempl. DO NOT EDIT.
// This file contains all queries for the database schema.
// ========================================
// Queries for table: catalog.category
// ========================================
func (q *Queries) GetCategory(ctx context.Context, arg GetCategoryParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, getCategory, arg.ID, arg.Name)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
	)
	return i, err
}

const getComment = `-- name: GetComment :one

SELECT id, account_id, order_id, ref_type, ref_id, body, upvote, downvote, score, date_created, date_updated
FROM "catalog"."comment"
WHERE ("id" = $1)
`

// ========================================
// Queries for table: catalog.comment
// ========================================
func (q *Queries) GetComment(ctx context.Context, id uuid.NullUUID) (CatalogComment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i CatalogComment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OrderID,
		&i.RefType,
		&i.RefID,
		&i.Body,
		&i.Upvote,
		&i.Downvote,
		&i.Score,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const getProductSku = `-- name: GetProductSku :one

SELECT id, spu_id, price, shared_packaging, attributes, package_details, date_created, date_deleted
FROM "catalog"."product_sku"
WHERE ("id" = $1)
`

// ========================================
// Queries for table: catalog.product_sku
// ========================================
func (q *Queries) GetProductSku(ctx context.Context, id uuid.NullUUID) (CatalogProductSku, error) {
	row := q.db.QueryRow(ctx, getProductSku, id)
	var i CatalogProductSku
	err := row.Scan(
		&i.ID,
		&i.SpuID,
		&i.Price,
		&i.SharedPackaging,
		&i.Attributes,
		&i.PackageDetails,
		&i.DateCreated,
		&i.DateDeleted,
	)
	return i, err
}

const getProductSpu = `-- name: GetProductSpu :one

SELECT id, number, slug, account_id, category_id, featured_sku_id, name, description, is_enabled, currency, specifications, date_created, date_updated, date_deleted, cached_price, cached_rating
FROM "catalog"."product_spu"
WHERE ("id" = $1) OR ("slug" = $2) OR ("featured_sku_id" = $3)
`

type GetProductSpuParams struct {
	ID            uuid.NullUUID `db:"id" json:"id"`
	Slug          null.String   `db:"slug" json:"slug"`
	FeaturedSkuID uuid.NullUUID `db:"featured_sku_id" json:"featured_sku_id"`
}

// ========================================
// Queries for table: catalog.product_spu
// ========================================
func (q *Queries) GetProductSpu(ctx context.Context, arg GetProductSpuParams) (CatalogProductSpu, error) {
	row := q.db.QueryRow(ctx, getProductSpu, arg.ID, arg.Slug, arg.FeaturedSkuID)
	var i CatalogProductSpu
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Slug,
		&i.AccountID,
		&i.CategoryID,
		&i.FeaturedSkuID,
		&i.Name,
		&i.Description,
		&i.IsEnabled,
		&i.Currency,
		&i.Specifications,
		&i.DateCreated,
		&i.DateUpdated,
		&i.DateDeleted,
		&i.CachedPrice,
		&i.CachedRating,
	)
	return i, err
}

const getProductSpuTag = `-- name: GetProductSpuTag :one

SELECT id, spu_id, tag
FROM "catalog"."product_spu_tag"
WHERE ("id" = $1) OR ("spu_id" = $2 AND "tag" = $3)
`

type GetProductSpuTagParams struct {
	ID    null.Int      `db:"id" json:"id"`
	SpuID uuid.NullUUID `db:"spu_id" json:"spu_id"`
	Tag   null.String   `db:"tag" json:"tag"`
}

// ========================================
// Queries for table: catalog.product_spu_tag
// ========================================
func (q *Queries) GetProductSpuTag(ctx context.Context, arg GetProductSpuTagParams) (CatalogProductSpuTag, error) {
	row := q.db.QueryRow(ctx, getProductSpuTag, arg.ID, arg.SpuID, arg.Tag)
	var i CatalogProductSpuTag
	err := row.Scan(&i.ID, &i.SpuID, &i.Tag)
	return i, err
}

const getSearchSync = `-- name: GetSearchSync :one

SELECT id, ref_type, ref_id, is_stale_embedding, date_created, date_updated
FROM "catalog"."search_sync"
WHERE ("id" = $1) OR ("ref_type" = $2 AND "ref_id" = $3)
`

type GetSearchSyncParams struct {
	ID      null.Int                     `db:"id" json:"id"`
	RefType NullCatalogSearchSyncRefType `db:"ref_type" json:"ref_type"`
	RefID   uuid.NullUUID                `db:"ref_id" json:"ref_id"`
}

// ========================================
// Queries for table: catalog.search_sync
// ========================================
func (q *Queries) GetSearchSync(ctx context.Context, arg GetSearchSyncParams) (CatalogSearchSync, error) {
	row := q.db.QueryRow(ctx, getSearchSync, arg.ID, arg.RefType, arg.RefID)
	var i CatalogSearchSync
	err := row.Scan(
		&i.ID,
		&i.RefType,
		&i.RefID,
		&i.IsStaleEmbedding,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const getTag = `-- name: GetTag :one

SELECT id, name, description
FROM "catalog"."tag"
WHERE ("id" = $1)
`

// ========================================
// Queries for table: catalog.tag
// ========================================
func (q *Queries) GetTag(ctx context.Context, id null.String) (CatalogTag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i CatalogTag
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE "catalog"."category"
SET "name" = COALESCE($1, "name"),
    "description" = COALESCE($2, "description"),
    "parent_id" = CASE WHEN $3::bool = TRUE THEN NULL ELSE COALESCE($4, "parent_id") END
WHERE "id" = $5
RETURNING id, name, description, parent_id
`

type UpdateCategoryParams struct {
	Name         null.String   `db:"name" json:"name"`
	Description  null.String   `db:"description" json:"description"`
	NullParentID bool          `db:"null_parent_id" json:"null_parent_id"`
	ParentID     uuid.NullUUID `db:"parent_id" json:"parent_id"`
	ID           uuid.UUID     `db:"id" json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Description,
		arg.NullParentID,
		arg.ParentID,
		arg.ID,
	)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ParentID,
	)
	return i, err
}

const updateComment = `-- name: UpdateComment :one
UPDATE "catalog"."comment"
SET "account_id" = COALESCE($1, "account_id"),
    "order_id" = CASE WHEN $2::bool = TRUE THEN NULL ELSE COALESCE($3, "order_id") END,
    "ref_type" = COALESCE($4, "ref_type"),
    "ref_id" = COALESCE($5, "ref_id"),
    "body" = COALESCE($6, "body"),
    "upvote" = COALESCE($7, "upvote"),
    "downvote" = COALESCE($8, "downvote"),
    "score" = COALESCE($9, "score"),
    "date_created" = COALESCE($10, "date_created"),
    "date_updated" = COALESCE($11, "date_updated")
WHERE "id" = $12
RETURNING id, account_id, order_id, ref_type, ref_id, body, upvote, downvote, score, date_created, date_updated
`

type UpdateCommentParams struct {
	AccountID   uuid.NullUUID             `db:"account_id" json:"account_id"`
	NullOrderID bool                      `db:"null_order_id" json:"null_order_id"`
	OrderID     uuid.NullUUID             `db:"order_id" json:"order_id"`
	RefType     NullCatalogCommentRefType `db:"ref_type" json:"ref_type"`
	RefID       uuid.NullUUID             `db:"ref_id" json:"ref_id"`
	Body        null.String               `db:"body" json:"body"`
	Upvote      null.Int                  `db:"upvote" json:"upvote"`
	Downvote    null.Int                  `db:"downvote" json:"downvote"`
	Score       null.Float                `db:"score" json:"score"`
	DateCreated null.Time                 `db:"date_created" json:"date_created"`
	DateUpdated null.Time                 `db:"date_updated" json:"date_updated"`
	ID          uuid.UUID                 `db:"id" json:"id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (CatalogComment, error) {
	row := q.db.QueryRow(ctx, updateComment,
		arg.AccountID,
		arg.NullOrderID,
		arg.OrderID,
		arg.RefType,
		arg.RefID,
		arg.Body,
		arg.Upvote,
		arg.Downvote,
		arg.Score,
		arg.DateCreated,
		arg.DateUpdated,
		arg.ID,
	)
	var i CatalogComment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OrderID,
		&i.RefType,
		&i.RefID,
		&i.Body,
		&i.Upvote,
		&i.Downvote,
		&i.Score,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const updateProductSku = `-- name: UpdateProductSku :one
UPDATE "catalog"."product_sku"
SET "spu_id" = COALESCE($1, "spu_id"),
    "price" = COALESCE($2, "price"),
    "shared_packaging" = COALESCE($3, "shared_packaging"),
    "attributes" = COALESCE($4, "attributes"),
    "package_details" = COALESCE($5, "package_details"),
    "date_created" = COALESCE($6, "date_created"),
    "date_deleted" = CASE WHEN $7::bool = TRUE THEN NULL ELSE COALESCE($8, "date_deleted") END
WHERE "id" = $9
RETURNING id, spu_id, price, shared_packaging, attributes, package_details, date_created, date_deleted
`

type UpdateProductSkuParams struct {
	SpuID           uuid.NullUUID   `db:"spu_id" json:"spu_id"`
	Price           null.Int        `db:"price" json:"price"`
	SharedPackaging null.Bool       `db:"shared_packaging" json:"shared_packaging"`
	Attributes      json.RawMessage `db:"attributes" json:"attributes"`
	PackageDetails  json.RawMessage `db:"package_details" json:"package_details"`
	DateCreated     null.Time       `db:"date_created" json:"date_created"`
	NullDateDeleted bool            `db:"null_date_deleted" json:"null_date_deleted"`
	DateDeleted     null.Time       `db:"date_deleted" json:"date_deleted"`
	ID              uuid.UUID       `db:"id" json:"id"`
}

func (q *Queries) UpdateProductSku(ctx context.Context, arg UpdateProductSkuParams) (CatalogProductSku, error) {
	row := q.db.QueryRow(ctx, updateProductSku,
		arg.SpuID,
		arg.Price,
		arg.SharedPackaging,
		arg.Attributes,
		arg.PackageDetails,
		arg.DateCreated,
		arg.NullDateDeleted,
		arg.DateDeleted,
		arg.ID,
	)
	var i CatalogProductSku
	err := row.Scan(
		&i.ID,
		&i.SpuID,
		&i.Price,
		&i.SharedPackaging,
		&i.Attributes,
		&i.PackageDetails,
		&i.DateCreated,
		&i.DateDeleted,
	)
	return i, err
}

const updateProductSpu = `-- name: UpdateProductSpu :one
UPDATE "catalog"."product_spu"
SET "slug" = COALESCE($1, "slug"),
    "account_id" = COALESCE($2, "account_id"),
    "category_id" = COALESCE($3, "category_id"),
    "featured_sku_id" = CASE WHEN $4::bool = TRUE THEN NULL ELSE COALESCE($5, "featured_sku_id") END,
    "name" = COALESCE($6, "name"),
    "description" = COALESCE($7, "description"),
    "is_enabled" = COALESCE($8, "is_enabled"),
    "currency" = COALESCE($9, "currency"),
    "specifications" = COALESCE($10, "specifications"),
    "date_created" = COALESCE($11, "date_created"),
    "date_updated" = COALESCE($12, "date_updated"),
    "date_deleted" = CASE WHEN $13::bool = TRUE THEN NULL ELSE COALESCE($14, "date_deleted") END,
    "cached_price" = COALESCE($15, "cached_price"),
    "cached_rating" = COALESCE($16, "cached_rating")
WHERE "id" = $17
RETURNING id, number, slug, account_id, category_id, featured_sku_id, name, description, is_enabled, currency, specifications, date_created, date_updated, date_deleted, cached_price, cached_rating
`

type UpdateProductSpuParams struct {
	Slug              null.String     `db:"slug" json:"slug"`
	AccountID         uuid.NullUUID   `db:"account_id" json:"account_id"`
	CategoryID        uuid.NullUUID   `db:"category_id" json:"category_id"`
	NullFeaturedSkuID bool            `db:"null_featured_sku_id" json:"null_featured_sku_id"`
	FeaturedSkuID     uuid.NullUUID   `db:"featured_sku_id" json:"featured_sku_id"`
	Name              null.String     `db:"name" json:"name"`
	Description       null.String     `db:"description" json:"description"`
	IsEnabled         null.Bool       `db:"is_enabled" json:"is_enabled"`
	Currency          null.String     `db:"currency" json:"currency"`
	Specifications    json.RawMessage `db:"specifications" json:"specifications"`
	DateCreated       null.Time       `db:"date_created" json:"date_created"`
	DateUpdated       null.Time       `db:"date_updated" json:"date_updated"`
	NullDateDeleted   bool            `db:"null_date_deleted" json:"null_date_deleted"`
	DateDeleted       null.Time       `db:"date_deleted" json:"date_deleted"`
	CachedPrice       null.Int        `db:"cached_price" json:"cached_price"`
	CachedRating      null.Float      `db:"cached_rating" json:"cached_rating"`
	ID                uuid.UUID       `db:"id" json:"id"`
}

func (q *Queries) UpdateProductSpu(ctx context.Context, arg UpdateProductSpuParams) (CatalogProductSpu, error) {
	row := q.db.QueryRow(ctx, updateProductSpu,
		arg.Slug,
		arg.AccountID,
		arg.CategoryID,
		arg.NullFeaturedSkuID,
		arg.FeaturedSkuID,
		arg.Name,
		arg.Description,
		arg.IsEnabled,
		arg.Currency,
		arg.Specifications,
		arg.DateCreated,
		arg.DateUpdated,
		arg.NullDateDeleted,
		arg.DateDeleted,
		arg.CachedPrice,
		arg.CachedRating,
		arg.ID,
	)
	var i CatalogProductSpu
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Slug,
		&i.AccountID,
		&i.CategoryID,
		&i.FeaturedSkuID,
		&i.Name,
		&i.Description,
		&i.IsEnabled,
		&i.Currency,
		&i.Specifications,
		&i.DateCreated,
		&i.DateUpdated,
		&i.DateDeleted,
		&i.CachedPrice,
		&i.CachedRating,
	)
	return i, err
}

const updateProductSpuTag = `-- name: UpdateProductSpuTag :one
UPDATE "catalog"."product_spu_tag"
SET "spu_id" = COALESCE($1, "spu_id"),
    "tag" = COALESCE($2, "tag")
WHERE "id" = $3
RETURNING id, spu_id, tag
`

type UpdateProductSpuTagParams struct {
	SpuID uuid.NullUUID `db:"spu_id" json:"spu_id"`
	Tag   null.String   `db:"tag" json:"tag"`
	ID    int64         `db:"id" json:"id"`
}

func (q *Queries) UpdateProductSpuTag(ctx context.Context, arg UpdateProductSpuTagParams) (CatalogProductSpuTag, error) {
	row := q.db.QueryRow(ctx, updateProductSpuTag, arg.SpuID, arg.Tag, arg.ID)
	var i CatalogProductSpuTag
	err := row.Scan(&i.ID, &i.SpuID, &i.Tag)
	return i, err
}

const updateSearchSync = `-- name: UpdateSearchSync :one
UPDATE "catalog"."search_sync"
SET "ref_type" = COALESCE($1, "ref_type"),
    "ref_id" = COALESCE($2, "ref_id"),
    "is_stale_embedding" = COALESCE($3, "is_stale_embedding"),
    "date_created" = COALESCE($4, "date_created"),
    "date_updated" = COALESCE($5, "date_updated")
WHERE "id" = $6
RETURNING id, ref_type, ref_id, is_stale_embedding, date_created, date_updated
`

type UpdateSearchSyncParams struct {
	RefType          NullCatalogSearchSyncRefType `db:"ref_type" json:"ref_type"`
	RefID            uuid.NullUUID                `db:"ref_id" json:"ref_id"`
	IsStaleEmbedding null.Bool                    `db:"is_stale_embedding" json:"is_stale_embedding"`
	DateCreated      null.Time                    `db:"date_created" json:"date_created"`
	DateUpdated      null.Time                    `db:"date_updated" json:"date_updated"`
	ID               int64                        `db:"id" json:"id"`
}

func (q *Queries) UpdateSearchSync(ctx context.Context, arg UpdateSearchSyncParams) (CatalogSearchSync, error) {
	row := q.db.QueryRow(ctx, updateSearchSync,
		arg.RefType,
		arg.RefID,
		arg.IsStaleEmbedding,
		arg.DateCreated,
		arg.DateUpdated,
		arg.ID,
	)
	var i CatalogSearchSync
	err := row.Scan(
		&i.ID,
		&i.RefType,
		&i.RefID,
		&i.IsStaleEmbedding,
		&i.DateCreated,
		&i.DateUpdated,
	)
	return i, err
}

const updateTag = `-- name: UpdateTag :one
UPDATE "catalog"."tag"
SET "name" = COALESCE($1, "name"),
    "description" = CASE WHEN $2::bool = TRUE THEN NULL ELSE COALESCE($3, "description") END
WHERE "id" = $4
RETURNING id, name, description
`

type UpdateTagParams struct {
	Name            null.String `db:"name" json:"name"`
	NullDescription bool        `db:"null_description" json:"null_description"`
	Description     null.String `db:"description" json:"description"`
	ID              string      `db:"id" json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (CatalogTag, error) {
	row := q.db.QueryRow(ctx, updateTag,
		arg.Name,
		arg.NullDescription,
		arg.Description,
		arg.ID,
	)
	var i CatalogTag
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
