// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search_sync.sql

package catalogdb

import (
	"context"

	"github.com/google/uuid"
)

const listStaleSearchSync = `-- name: ListStaleSearchSync :many
SELECT id, ref_id, ref_type
FROM catalog.search_sync
WHERE is_stale_embedding = true
ORDER BY date_updated ASC
FOR UPDATE SKIP LOCKED
LIMIT $1
`

type ListStaleSearchSyncRow struct {
	ID      int64                    `json:"id"`
	RefID   uuid.UUID                `json:"ref_id"`
	RefType CatalogSearchSyncRefType `json:"ref_type"`
}

func (q *Queries) ListStaleSearchSync(ctx context.Context, limit int32) ([]ListStaleSearchSyncRow, error) {
	rows, err := q.db.Query(ctx, listStaleSearchSync, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleSearchSyncRow{}
	for rows.Next() {
		var i ListStaleSearchSyncRow
		if err := rows.Scan(&i.ID, &i.RefID, &i.RefType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleSearchSync = `-- name: MarkStaleSearchSync :exec
UPDATE catalog.search_sync
SET is_stale_embedding = true, date_updated = NOW()
WHERE ref_type = $1 AND ref_id = $2
`

type MarkStaleSearchSyncParams struct {
	RefType CatalogSearchSyncRefType `json:"ref_type"`
	RefID   uuid.UUID                `json:"ref_id"`
}

func (q *Queries) MarkStaleSearchSync(ctx context.Context, arg MarkStaleSearchSyncParams) error {
	_, err := q.db.Exec(ctx, markStaleSearchSync, arg.RefType, arg.RefID)
	return err
}
