// Code generated by pgtempl; DO NOT EDIT.
package orderrepo

import (
	"context"
	"strings"

	"github.com/jackc/pgx/v5"
	"shopnexus-server/internal/shared/patch"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
	orderdb "shopnexus-server/internal/module/order/db/sqlc"
	"time"
)

type CreateRefundParams struct {
	AccountID                uuid.UUID
	OrderID                  uuid.UUID
	Reason                   string
	ReturnTransportID        int64
	DateReceivedBySeller     null.Time
	ReviewDeadline           null.Time
	SellerDecisionAt         null.Time
	ReturnToBuyerTransportID null.Int
	RejectionReason          null.String
	RefundTxID               uuid.NullUUID
}

func (r *Repository) CreateRefund(ctx context.Context, arg CreateRefundParams) (uuid.UUID, error) {
	var pk uuid.UUID
	err := r.db.QueryRow(ctx, `INSERT INTO "order"."refund" ("account_id", "order_id", "reason", "return_transport_id", "date_received_by_seller", "review_deadline", "seller_decision_at", "return_to_buyer_transport_id", "rejection_reason", "refund_tx_id")
		VALUES (@account_id, @order_id, @reason, @return_transport_id, @date_received_by_seller, @review_deadline, @seller_decision_at, @return_to_buyer_transport_id, @rejection_reason, @refund_tx_id)
		RETURNING "id"`,
		pgx.NamedArgs{"account_id": arg.AccountID, "order_id": arg.OrderID, "reason": arg.Reason, "return_transport_id": arg.ReturnTransportID, "date_received_by_seller": arg.DateReceivedBySeller, "review_deadline": arg.ReviewDeadline, "seller_decision_at": arg.SellerDecisionAt, "return_to_buyer_transport_id": arg.ReturnToBuyerTransportID, "rejection_reason": arg.RejectionReason, "refund_tx_id": arg.RefundTxID}).Scan(&pk)
	return pk, err
}

func (r *Repository) GetRefund(ctx context.Context, id uuid.UUID) (Refund, error) {
	var i Refund
	err := r.db.QueryRow(ctx, `SELECT "id", "account_id", "order_id", "reason", "date_created", "status", "return_transport_id", "date_received_by_seller", "review_deadline", "seller_decision_at", "return_to_buyer_transport_id", "rejection_reason", "refund_tx_id" FROM "order"."refund" WHERE "id" = @id`,
		pgx.NamedArgs{"id": id}).Scan(&i.ID, &i.AccountID, &i.OrderID, &i.Reason, &i.DateCreated, &i.Status, &i.ReturnTransportID, &i.DateReceivedBySeller, &i.ReviewDeadline, &i.SellerDecisionAt, &i.ReturnToBuyerTransportID, &i.RejectionReason, &i.RefundTxID)
	return i, err
}

type UpdateRefundParams struct {
	AccountID                patch.Optional[uuid.UUID]
	OrderID                  patch.Optional[uuid.UUID]
	Reason                   patch.Optional[string]
	DateCreated              patch.Optional[time.Time]
	Status                   patch.Optional[orderdb.OrderRefundStatus]
	ReturnTransportID        patch.Optional[int64]
	DateReceivedBySeller     patch.Optional[null.Time]
	ReviewDeadline           patch.Optional[null.Time]
	SellerDecisionAt         patch.Optional[null.Time]
	ReturnToBuyerTransportID patch.Optional[null.Int]
	RejectionReason          patch.Optional[null.String]
	RefundTxID               patch.Optional[uuid.NullUUID]
}

func (r *Repository) UpdateRefund(ctx context.Context, id uuid.UUID, arg UpdateRefundParams) (uuid.UUID, error) {
	set := make([]string, 0, 12)
	args := pgx.NamedArgs{"id": id}
	if arg.AccountID.Set {
		set = append(set, `"account_id" = @account_id`)
		args["account_id"] = arg.AccountID.Value
	}
	if arg.OrderID.Set {
		set = append(set, `"order_id" = @order_id`)
		args["order_id"] = arg.OrderID.Value
	}
	if arg.Reason.Set {
		set = append(set, `"reason" = @reason`)
		args["reason"] = arg.Reason.Value
	}
	if arg.DateCreated.Set {
		set = append(set, `"date_created" = @date_created`)
		args["date_created"] = arg.DateCreated.Value
	}
	if arg.Status.Set {
		set = append(set, `"status" = @status`)
		args["status"] = arg.Status.Value
	}
	if arg.ReturnTransportID.Set {
		set = append(set, `"return_transport_id" = @return_transport_id`)
		args["return_transport_id"] = arg.ReturnTransportID.Value
	}
	if arg.DateReceivedBySeller.Set {
		set = append(set, `"date_received_by_seller" = @date_received_by_seller`)
		args["date_received_by_seller"] = arg.DateReceivedBySeller.Value
	}
	if arg.ReviewDeadline.Set {
		set = append(set, `"review_deadline" = @review_deadline`)
		args["review_deadline"] = arg.ReviewDeadline.Value
	}
	if arg.SellerDecisionAt.Set {
		set = append(set, `"seller_decision_at" = @seller_decision_at`)
		args["seller_decision_at"] = arg.SellerDecisionAt.Value
	}
	if arg.ReturnToBuyerTransportID.Set {
		set = append(set, `"return_to_buyer_transport_id" = @return_to_buyer_transport_id`)
		args["return_to_buyer_transport_id"] = arg.ReturnToBuyerTransportID.Value
	}
	if arg.RejectionReason.Set {
		set = append(set, `"rejection_reason" = @rejection_reason`)
		args["rejection_reason"] = arg.RejectionReason.Value
	}
	if arg.RefundTxID.Set {
		set = append(set, `"refund_tx_id" = @refund_tx_id`)
		args["refund_tx_id"] = arg.RefundTxID.Value
	}
	if len(set) == 0 {
		return id, nil
	}
	sql := `UPDATE "order"."refund" SET ` + strings.Join(set, ", ") + ` WHERE "id" = @id RETURNING "id"`
	var pk uuid.UUID
	err := r.db.QueryRow(ctx, sql, args).Scan(&pk)
	return pk, err
}

func (r *Repository) DeleteRefund(ctx context.Context, id uuid.UUID) error {
	_, err := r.db.Exec(ctx, `DELETE FROM "order"."refund" WHERE "id" = @id`, pgx.NamedArgs{"id": id})
	return err
}
