// Code generated by pgtempl; DO NOT EDIT.
package orderrepo

import (
	"context"
	"strings"

	"github.com/jackc/pgx/v5"
	"shopnexus-server/internal/shared/patch"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
	"time"
)

type CreateOrderParams struct {
	BuyerID          uuid.UUID
	SellerID         uuid.UUID
	TransportID      int64
	Address          string
	ConfirmedByID    uuid.UUID
	ConfirmSessionID uuid.UUID
	Note             null.String
}

func (r *Repository) CreateOrder(ctx context.Context, arg CreateOrderParams) (uuid.UUID, error) {
	var pk uuid.UUID
	err := r.db.QueryRow(ctx, `INSERT INTO "order"."order" ("buyer_id", "seller_id", "transport_id", "address", "confirmed_by_id", "confirm_session_id", "note")
		VALUES (@buyer_id, @seller_id, @transport_id, @address, @confirmed_by_id, @confirm_session_id, @note)
		RETURNING "id"`,
		pgx.NamedArgs{"buyer_id": arg.BuyerID, "seller_id": arg.SellerID, "transport_id": arg.TransportID, "address": arg.Address, "confirmed_by_id": arg.ConfirmedByID, "confirm_session_id": arg.ConfirmSessionID, "note": arg.Note}).Scan(&pk)
	return pk, err
}

func (r *Repository) GetOrder(ctx context.Context, id uuid.UUID) (Order, error) {
	var i Order
	err := r.db.QueryRow(ctx, `SELECT "id", "buyer_id", "seller_id", "transport_id", "address", "date_created", "confirmed_by_id", "confirm_session_id", "note" FROM "order"."order" WHERE "id" = @id`,
		pgx.NamedArgs{"id": id}).Scan(&i.ID, &i.BuyerID, &i.SellerID, &i.TransportID, &i.Address, &i.DateCreated, &i.ConfirmedByID, &i.ConfirmSessionID, &i.Note)
	return i, err
}

type UpdateOrderParams struct {
	BuyerID          patch.Optional[uuid.UUID]
	SellerID         patch.Optional[uuid.UUID]
	TransportID      patch.Optional[int64]
	Address          patch.Optional[string]
	DateCreated      patch.Optional[time.Time]
	ConfirmedByID    patch.Optional[uuid.UUID]
	ConfirmSessionID patch.Optional[uuid.UUID]
	Note             patch.Optional[null.String]
}

func (r *Repository) UpdateOrder(ctx context.Context, id uuid.UUID, arg UpdateOrderParams) (uuid.UUID, error) {
	set := make([]string, 0, 8)
	args := pgx.NamedArgs{"id": id}
	if arg.BuyerID.Set {
		set = append(set, `"buyer_id" = @buyer_id`)
		args["buyer_id"] = arg.BuyerID.Value
	}
	if arg.SellerID.Set {
		set = append(set, `"seller_id" = @seller_id`)
		args["seller_id"] = arg.SellerID.Value
	}
	if arg.TransportID.Set {
		set = append(set, `"transport_id" = @transport_id`)
		args["transport_id"] = arg.TransportID.Value
	}
	if arg.Address.Set {
		set = append(set, `"address" = @address`)
		args["address"] = arg.Address.Value
	}
	if arg.DateCreated.Set {
		set = append(set, `"date_created" = @date_created`)
		args["date_created"] = arg.DateCreated.Value
	}
	if arg.ConfirmedByID.Set {
		set = append(set, `"confirmed_by_id" = @confirmed_by_id`)
		args["confirmed_by_id"] = arg.ConfirmedByID.Value
	}
	if arg.ConfirmSessionID.Set {
		set = append(set, `"confirm_session_id" = @confirm_session_id`)
		args["confirm_session_id"] = arg.ConfirmSessionID.Value
	}
	if arg.Note.Set {
		set = append(set, `"note" = @note`)
		args["note"] = arg.Note.Value
	}
	if len(set) == 0 {
		return id, nil
	}
	sql := `UPDATE "order"."order" SET ` + strings.Join(set, ", ") + ` WHERE "id" = @id RETURNING "id"`
	var pk uuid.UUID
	err := r.db.QueryRow(ctx, sql, args).Scan(&pk)
	return pk, err
}

func (r *Repository) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	_, err := r.db.Exec(ctx, `DELETE FROM "order"."order" WHERE "id" = @id`, pgx.NamedArgs{"id": id})
	return err
}
