// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package promotiondb

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	null "github.com/guregu/null/v6"
)

type PromotionRefType string

const (
	PromotionRefTypeProductSpu PromotionRefType = "ProductSpu"
	PromotionRefTypeProductSku PromotionRefType = "ProductSku"
	PromotionRefTypeCategory   PromotionRefType = "Category"
)

func (e *PromotionRefType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromotionRefType(s)
	case string:
		*e = PromotionRefType(s)
	default:
		return fmt.Errorf("unsupported scan type for PromotionRefType: %T", src)
	}
	return nil
}

type NullPromotionRefType struct {
	PromotionRefType PromotionRefType `json:"promotion_ref_type"`
	Valid            bool             `json:"valid"` // Valid is true if PromotionRefType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromotionRefType) Scan(value interface{}) error {
	if value == nil {
		ns.PromotionRefType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromotionRefType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromotionRefType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromotionRefType), nil
}

func (e PromotionRefType) Valid() bool {
	switch e {
	case PromotionRefTypeProductSpu,
		PromotionRefTypeProductSku,
		PromotionRefTypeCategory:
		return true
	}
	return false
}

func AllPromotionRefTypeValues() []PromotionRefType {
	return []PromotionRefType{
		PromotionRefTypeProductSpu,
		PromotionRefTypeProductSku,
		PromotionRefTypeCategory,
	}
}

type PromotionType string

const (
	PromotionTypeDiscount     PromotionType = "Discount"
	PromotionTypeShipDiscount PromotionType = "ShipDiscount"
	PromotionTypeBundle       PromotionType = "Bundle"
	PromotionTypeBuyXGetY     PromotionType = "BuyXGetY"
	PromotionTypeCashback     PromotionType = "Cashback"
)

func (e *PromotionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromotionType(s)
	case string:
		*e = PromotionType(s)
	default:
		return fmt.Errorf("unsupported scan type for PromotionType: %T", src)
	}
	return nil
}

type NullPromotionType struct {
	PromotionType PromotionType `json:"promotion_type"`
	Valid         bool          `json:"valid"` // Valid is true if PromotionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromotionType) Scan(value interface{}) error {
	if value == nil {
		ns.PromotionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromotionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromotionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromotionType), nil
}

func (e PromotionType) Valid() bool {
	switch e {
	case PromotionTypeDiscount,
		PromotionTypeShipDiscount,
		PromotionTypeBundle,
		PromotionTypeBuyXGetY,
		PromotionTypeCashback:
		return true
	}
	return false
}

func AllPromotionTypeValues() []PromotionType {
	return []PromotionType{
		PromotionTypeDiscount,
		PromotionTypeShipDiscount,
		PromotionTypeBundle,
		PromotionTypeBuyXGetY,
		PromotionTypeCashback,
	}
}

type PromotionPromotion struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	Code        string          `db:"code" json:"code"`
	OwnerID     uuid.NullUUID   `db:"owner_id" json:"owner_id"`
	Type        PromotionType   `db:"type" json:"type"`
	Title       string          `db:"title" json:"title"`
	Description null.String     `db:"description" json:"description"`
	IsEnabled   bool            `db:"is_enabled" json:"is_enabled"`
	Budget      int64           `db:"budget" json:"budget"`
	AutoApply   bool            `db:"auto_apply" json:"auto_apply"`
	Group       string          `db:"group" json:"group"`
	Data        json.RawMessage `db:"data" json:"data"`
	DateStarted time.Time       `db:"date_started" json:"date_started"`
	DateEnded   null.Time       `db:"date_ended" json:"date_ended"`
	DateCreated time.Time       `db:"date_created" json:"date_created"`
	DateUpdated time.Time       `db:"date_updated" json:"date_updated"`
}

type PromotionRef struct {
	ID          int64            `db:"id" json:"id"`
	PromotionID uuid.UUID        `db:"promotion_id" json:"promotion_id"`
	RefType     PromotionRefType `db:"ref_type" json:"ref_type"`
	RefID       uuid.UUID        `db:"ref_id" json:"ref_id"`
}

type PromotionSchedule struct {
	ID          int64     `db:"id" json:"id"`
	PromotionID uuid.UUID `db:"promotion_id" json:"promotion_id"`
	Timezone    string    `db:"timezone" json:"timezone"`
	CronRule    string    `db:"cron_rule" json:"cron_rule"`
	Duration    int32     `db:"duration" json:"duration"`
	NextRunAt   null.Time `db:"next_run_at" json:"next_run_at"`
	LastRunAt   null.Time `db:"last_run_at" json:"last_run_at"`
}

func (n NullPromotionRefType) MarshalJSON() ([]byte, error) {
	if !n.Valid {
		return []byte("null"), nil
	}
	return json.Marshal(n.PromotionRefType)
}
func (n *NullPromotionRefType) UnmarshalJSON(b []byte) error {
	if string(b) == "null" {
		n.Valid = false
		return nil
	}
	n.Valid = true
	return json.Unmarshal(b, &n.PromotionRefType)
}
func (n NullPromotionType) MarshalJSON() ([]byte, error) {
	if !n.Valid {
		return []byte("null"), nil
	}
	return json.Marshal(n.PromotionType)
}
func (n *NullPromotionType) UnmarshalJSON(b []byte) error {
	if string(b) == "null" {
		n.Valid = false
		return nil
	}
	n.Valid = true
	return json.Unmarshal(b, &n.PromotionType)
}
