// Code generated by cmd/nullmarshal. DO NOT EDIT.

package promotiondb

import "encoding/json"

func (n NullPromotionRefType) MarshalJSON() ([]byte, error) {
	if !n.Valid {
		return []byte("null"), nil
	}
	return json.Marshal(n.PromotionRefType)
}

func (n *NullPromotionRefType) UnmarshalJSON(b []byte) error {
	if string(b) == "null" {
		n.Valid = false
		return nil
	}
	n.Valid = true
	return json.Unmarshal(b, &n.PromotionRefType)
}

func (n NullPromotionType) MarshalJSON() ([]byte, error) {
	if !n.Valid {
		return []byte("null"), nil
	}
	return json.Marshal(n.PromotionType)
}

func (n *NullPromotionType) UnmarshalJSON(b []byte) error {
	if string(b) == "null" {
		n.Valid = false
		return nil
	}
	n.Valid = true
	return json.Unmarshal(b, &n.PromotionType)
}
