-- =============================================
-- Module:      order
-- File:        dispute_custom.sql
-- Purpose:     Refund dispute v2 — seller-initiated escalation, admin resolves.
-- =============================================
-- Create/Get auto-generated by pgtempl (CreateDefaultRefundDispute / GetRefundDispute).

-- OpenRefundDispute inserts the seller's escalation. Status defaults to
-- 'Open' via the table default; admin will transition to SellerWins or
-- BuyerWins via ResolveRefundDispute. Named OpenRefundDispute to avoid
-- collision with pgtempl's auto-generated CreateRefundDispute. Evidence
-- photos attach separately via the common resource system (RefType=ReturnDispute).
-- name: OpenRefundDispute :one
INSERT INTO "order"."refund_dispute" (
    "refund_id", "account_id", "reason"
) VALUES (
    @refund_id, @account_id, @reason
)
RETURNING *;

-- ResolveRefundDispute closes an Open dispute with the admin's verdict.
-- Status must be either SellerWins or BuyerWins; the companion refund row
-- update happens in the same biz transaction via AdminUphold/AdminDismiss.
-- name: ResolveRefundDispute :one
UPDATE "order"."refund_dispute"
SET "status" = @status,
    "resolved_by_id" = @resolved_by_id,
    "resolution_note" = @resolution_note,
    "date_resolved" = CURRENT_TIMESTAMP
WHERE "id" = @id AND "status" = 'Open'
RETURNING *;

-- ListRefundDisputes powers the admin queue, with COUNT(*) OVER() for
-- page-based pagination. Filters by status; admins see everything,
-- buyers/sellers see their own.
-- name: ListRefundDisputes :many
SELECT sqlc.embed(embed_refund_dispute), COUNT(*) OVER() AS total_count
FROM "order"."refund_dispute" embed_refund_dispute
JOIN "order"."refund" r ON r."id" = embed_refund_dispute."refund_id"
JOIN "order"."order" o ON o."id" = r."order_id"
WHERE (sqlc.narg('status')::"order"."dispute_status" IS NULL OR embed_refund_dispute."status" = sqlc.narg('status'))
  AND (sqlc.narg('refund_id')::UUID IS NULL OR embed_refund_dispute."refund_id" = sqlc.narg('refund_id'))
  AND (
       sqlc.narg('caller_buyer_id')::UUID IS NULL
    OR r."account_id" = sqlc.narg('caller_buyer_id')
    OR o."seller_id"   = sqlc.narg('caller_seller_id')
  )
ORDER BY embed_refund_dispute."date_created" DESC
LIMIT sqlc.narg('limit')::INTEGER OFFSET sqlc.narg('offset')::INTEGER;
