-- =============================================
-- Module:      order
-- File:        refund_custom.sql
-- Purpose:     Refund v2 — buyer ships return at create time, seller decides
--              within 3D of delivery (auto-accept on timeout), seller may
--              dispute to admin.
-- =============================================
-- Create/Get auto-generated by pgtempl (CreateDefaultRefund / GetRefund).

-- CreateBuyerRefund inserts the initial Shipping row. Evidence photos attach
-- separately via the common resource system (RefType=Refund); the return-leg
-- transport ID is already provisioned by the biz layer.
-- name: CreateBuyerRefund :one
INSERT INTO "order"."refund" (
    "account_id", "order_id", "reason", "return_transport_id"
) VALUES (
    @account_id, @order_id, @reason, @return_transport_id
)
RETURNING *;

-- WithdrawBuyerRefund cancels a refund while it is still in Shipping.
-- Once the goods reach the seller (AwaitingSellerReview), withdraw is no
-- longer possible — biz layer rejects the call before reaching this SQL.
-- name: WithdrawBuyerRefund :one
UPDATE "order"."refund"
SET "status" = 'Cancelled'
WHERE "id" = @id
  AND "account_id" = @account_id
  AND "status" = 'Shipping'
RETURNING *;

-- MarkRefundDelivered fires when the forward (return) transport reaches its
-- final delivered state, flipping the refund into AwaitingSellerReview and
-- arming the 3-day auto-accept deadline.
-- name: MarkRefundDelivered :one
UPDATE "order"."refund"
SET "status" = 'AwaitingSellerReview',
    "date_received_by_seller" = CURRENT_TIMESTAMP,
    "review_deadline" = @review_deadline
WHERE "id" = @id AND "status" = 'Shipping'
RETURNING *;

-- SellerApproveRefund transitions AwaitingSellerReview → Accepted and stamps
-- the refund_tx_id pointing at the negative ledger leg the biz layer just
-- inserted. Same SQL is used for auto-accept on deadline (caller passes the
-- system's UUID or NULL for the implicit decider).
-- name: SellerApproveRefund :one
UPDATE "order"."refund"
SET "status" = 'Accepted',
    "seller_decision_at" = CURRENT_TIMESTAMP,
    "refund_tx_id" = @refund_tx_id
WHERE "id" = @id AND "status" = 'AwaitingSellerReview'
RETURNING *;

-- SellerDisputeRefund transitions AwaitingSellerReview → Disputed when the
-- seller refuses the refund. A companion row is inserted into refund_dispute
-- in the same biz call.
-- name: SellerDisputeRefund :one
UPDATE "order"."refund"
SET "status" = 'Disputed',
    "seller_decision_at" = CURRENT_TIMESTAMP
WHERE "id" = @id AND "status" = 'AwaitingSellerReview'
RETURNING *;

-- AdminDismissDispute: admin sides with the buyer → refund flips
-- Disputed → Accepted and the credit ledger leg is recorded.
-- name: AdminDismissDispute :one
UPDATE "order"."refund"
SET "status" = 'Accepted',
    "refund_tx_id" = @refund_tx_id
WHERE "id" = @id AND "status" = 'Disputed'
RETURNING *;

-- AdminUpholdDispute: admin sides with the seller → refund flips
-- Disputed → Rejected and the return-to-buyer transport is recorded so the
-- workflow can track delivery of the goods back.
-- name: AdminUpholdDispute :one
UPDATE "order"."refund"
SET "status" = 'Rejected',
    "return_to_buyer_transport_id" = @return_to_buyer_transport_id,
    "rejection_reason" = @rejection_reason
WHERE "id" = @id AND "status" = 'Disputed'
RETURNING *;

-- HasActiveRefundForOrder reports whether any refund row for this order is
-- still in negotiation (not yet Accepted or Rejected). Used by the fulfillment
-- workflow to decide whether to release escrow.
-- name: HasActiveRefundForOrder :one
SELECT EXISTS (
    SELECT 1 FROM "order"."refund"
    WHERE "order_id" = @order_id
      AND "status" IN ('Shipping', 'AwaitingSellerReview', 'Disputed')
) AS has_active;

-- GetRefundSnapshotByOrder is the per-iteration projection the fulfillment
-- workflow reads while watching escrow. has_active_refund flips while any
-- refund is in negotiation; last_refund_approved becomes true once the most
-- recent refund row for this order lands in Accepted; active_refund_id is the
-- refund the workflow must resolve inline (zero UUID when none active).
-- name: GetRefundSnapshotByOrder :one
WITH all_refunds AS (
    SELECT "id", "status", "date_created"
    FROM "order"."refund"
    WHERE "order_id" = @order_id
)
SELECT
    EXISTS (
        SELECT 1 FROM all_refunds
        WHERE "status" IN ('Shipping', 'AwaitingSellerReview', 'Disputed')
    )::BOOLEAN AS has_active_refund,
    COALESCE(
        (SELECT "status" FROM all_refunds ORDER BY "date_created" DESC LIMIT 1) = 'Accepted'::"order"."refund_status",
        false
    )::BOOLEAN AS last_refund_approved,
    COALESCE(
        (
            SELECT "id" FROM all_refunds
            WHERE "status" IN ('Shipping', 'AwaitingSellerReview', 'Disputed')
            ORDER BY "date_created" DESC LIMIT 1
        ),
        '00000000-0000-0000-0000-000000000000'::uuid
    )::uuid AS active_refund_id;

-- ListSellerRefunds returns refunds raised against orders the seller fulfilled,
-- newest first, with COUNT(*) OVER() for page-based pagination. Buyer-side
-- listing uses the generated ListCountRefund (account_id filter, no join).
-- name: ListSellerRefunds :many
SELECT sqlc.embed(embed_refund), COUNT(*) OVER() AS total_count
FROM "order"."refund" embed_refund
JOIN "order"."order" o ON o."id" = embed_refund."order_id"
WHERE o."seller_id" = @seller_id
ORDER BY embed_refund."date_created" DESC
LIMIT sqlc.narg('limit')::INTEGER OFFSET sqlc.narg('offset')::INTEGER;
