// Code generated by pgtempl; DO NOT EDIT.
package orderdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5"

	"shopnexus-server/internal/shared/paginate"
	"shopnexus-server/internal/shared/repolist"
)

// ListTransactionParams filters "order"."transaction". Each slice field is an IN/ANY match;
// *From/*To pairs are inclusive range bounds. Zero value = no filter.
type ListTransactionParams struct {
	paginate.Params

	Id              []uuid.UUID
	SessionId       []uuid.UUID
	Status          []OrderStatus
	Note            []string
	Error           []string
	PaymentOption   []string
	Amount          []int64
	AmountFrom      null.Int
	AmountTo        null.Int
	Currency        []string
	ReversesId      []uuid.UUID
	DateCreated     []time.Time
	DateCreatedFrom null.Time
	DateCreatedTo   null.Time
	DateSettled     []time.Time
	DateSettledFrom null.Time
	DateSettledTo   null.Time
	DateExpired     []time.Time
	DateExpiredFrom null.Time
	DateExpiredTo   null.Time
}

func transactionListConds(f ListTransactionParams, conds *[]string, args pgx.NamedArgs) {
	if len(f.Id) > 0 {
		*conds = append(*conds, `"id" = ANY(@id)`)
		args["id"] = f.Id
	}
	if len(f.SessionId) > 0 {
		*conds = append(*conds, `"session_id" = ANY(@session_id)`)
		args["session_id"] = f.SessionId
	}
	if len(f.Status) > 0 {
		*conds = append(*conds, `"status" = ANY(@status)`)
		args["status"] = f.Status
	}
	if len(f.Note) > 0 {
		*conds = append(*conds, `"note" = ANY(@note)`)
		args["note"] = f.Note
	}
	if len(f.Error) > 0 {
		*conds = append(*conds, `"error" = ANY(@error)`)
		args["error"] = f.Error
	}
	if len(f.PaymentOption) > 0 {
		*conds = append(*conds, `"payment_option" = ANY(@payment_option)`)
		args["payment_option"] = f.PaymentOption
	}
	if len(f.Amount) > 0 {
		*conds = append(*conds, `"amount" = ANY(@amount)`)
		args["amount"] = f.Amount
	}
	if f.AmountFrom.Valid {
		*conds = append(*conds, `"amount" >= @amount_from`)
		args["amount_from"] = f.AmountFrom.Int64
	}
	if f.AmountTo.Valid {
		*conds = append(*conds, `"amount" <= @amount_to`)
		args["amount_to"] = f.AmountTo.Int64
	}
	if len(f.Currency) > 0 {
		*conds = append(*conds, `"currency" = ANY(@currency)`)
		args["currency"] = f.Currency
	}
	if len(f.ReversesId) > 0 {
		*conds = append(*conds, `"reverses_id" = ANY(@reverses_id)`)
		args["reverses_id"] = f.ReversesId
	}
	if len(f.DateCreated) > 0 {
		*conds = append(*conds, `"date_created" = ANY(@date_created)`)
		args["date_created"] = f.DateCreated
	}
	if f.DateCreatedFrom.Valid {
		*conds = append(*conds, `"date_created" >= @date_created_from`)
		args["date_created_from"] = f.DateCreatedFrom.Time
	}
	if f.DateCreatedTo.Valid {
		*conds = append(*conds, `"date_created" <= @date_created_to`)
		args["date_created_to"] = f.DateCreatedTo.Time
	}
	if len(f.DateSettled) > 0 {
		*conds = append(*conds, `"date_settled" = ANY(@date_settled)`)
		args["date_settled"] = f.DateSettled
	}
	if f.DateSettledFrom.Valid {
		*conds = append(*conds, `"date_settled" >= @date_settled_from`)
		args["date_settled_from"] = f.DateSettledFrom.Time
	}
	if f.DateSettledTo.Valid {
		*conds = append(*conds, `"date_settled" <= @date_settled_to`)
		args["date_settled_to"] = f.DateSettledTo.Time
	}
	if len(f.DateExpired) > 0 {
		*conds = append(*conds, `"date_expired" = ANY(@date_expired)`)
		args["date_expired"] = f.DateExpired
	}
	if f.DateExpiredFrom.Valid {
		*conds = append(*conds, `"date_expired" >= @date_expired_from`)
		args["date_expired_from"] = f.DateExpiredFrom.Time
	}
	if f.DateExpiredTo.Valid {
		*conds = append(*conds, `"date_expired" <= @date_expired_to`)
		args["date_expired_to"] = f.DateExpiredTo.Time
	}
}

func transactionListSpec(f ListTransactionParams) repolist.Spec[OrderTransaction] {
	return repolist.Spec[OrderTransaction]{
		Table: `"order"."transaction"`,
		PK:    "id",
		Whitelist: paginate.Whitelist{
			"id":           {Col: `"id"`, Cast: "uuid"},
			"amount":       {Col: `"amount"`, Cast: "int8"},
			"date_created": {Col: `"date_created"`, Cast: "timestamptz"},
		},
		BindConds: func(conds *[]string, args pgx.NamedArgs) { transactionListConds(f, conds, args) },
	}
}

// ListTransaction runs offset (?page) or cursor (?cursor/?sort) pagination over "order"."transaction".
func (q *Queries) ListTransaction(ctx context.Context, f ListTransactionParams) (paginate.PaginateResult[OrderTransaction], error) {
	return repolist.List(ctx, q.db, transactionListSpec(f), f.Params)
}
