// Code generated by pgtempl; DO NOT EDIT.
package orderdb

import (
	"context"
	"time"

	"github.com/guregu/null/v6"
	"github.com/jackc/pgx/v5"

	"shopnexus-server/internal/shared/paginate"
	"shopnexus-server/internal/shared/repolist"
)

// ListTransportParams filters "order"."transport". A slice field is an IN/ANY match: nil = skip,
// non-nil empty = match nothing. *From/*To pairs are inclusive range bounds.
type ListTransportParams struct {
	paginate.Params

	Id              []int64
	Option          []string
	Status          []OrderStatus
	DateCreated     []time.Time
	DateCreatedFrom null.Time
	DateCreatedTo   null.Time
}

func transportListConds(f ListTransportParams, conds *[]string, args pgx.NamedArgs) {
	if f.Id != nil {
		*conds = append(*conds, `"id" = ANY(@id)`)
		args["id"] = f.Id
	}
	if f.Option != nil {
		*conds = append(*conds, `"option" = ANY(@option)`)
		args["option"] = f.Option
	}
	if f.Status != nil {
		*conds = append(*conds, `"status" = ANY(@status)`)
		args["status"] = f.Status
	}
	if f.DateCreated != nil {
		*conds = append(*conds, `"date_created" = ANY(@date_created)`)
		args["date_created"] = f.DateCreated
	}
	if f.DateCreatedFrom.Valid {
		*conds = append(*conds, `"date_created" >= @date_created_from`)
		args["date_created_from"] = f.DateCreatedFrom.Time
	}
	if f.DateCreatedTo.Valid {
		*conds = append(*conds, `"date_created" <= @date_created_to`)
		args["date_created_to"] = f.DateCreatedTo.Time
	}
}

func transportListSpec(f ListTransportParams) repolist.Spec[OrderTransport] {
	return repolist.Spec[OrderTransport]{
		Table: `"order"."transport"`,
		PK:    "id",
		Whitelist: paginate.Whitelist{
			"id":           {Col: `"id"`, Cast: "int8"},
			"date_created": {Col: `"date_created"`, Cast: "timestamptz"},
		},
		BindConds: func(conds *[]string, args pgx.NamedArgs) { transportListConds(f, conds, args) },
	}
}

// ListTransport runs offset (?page) or cursor (?cursor/?sort) pagination over "order"."transport".
func (q *Queries) ListTransport(ctx context.Context, f ListTransportParams) (paginate.PaginateResult[OrderTransport], error) {
	return repolist.List(ctx, q.db, transportListSpec(f), f.Params)
}
