// Code generated by pgtempl; DO NOT EDIT.
package orderdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/guregu/null/v6"

	"shopnexus-server/internal/shared/paginate"
	"shopnexus-server/internal/shared/repolist"
)

// ListOrderParams filters "order"."order". A slice field is an IN/ANY match: nil = skip,
// non-nil empty = match nothing. *From/*To pairs are inclusive range bounds.
type ListOrderParams struct {
	paginate.Params

	Id               []uuid.UUID
	BuyerId          []uuid.UUID
	SellerId         []uuid.UUID
	TransportId      []int64
	Address          []string
	DateCreated      []time.Time
	DateCreatedFrom  null.Time
	DateCreatedTo    null.Time
	ConfirmedById    []uuid.UUID
	ConfirmSessionId []uuid.UUID
	Note             []string
}

// OrderQuery is the reusable base listing for "order"."order".
func OrderQuery() repolist.Query[OrderOrder] {
	return repolist.Query[OrderOrder]{
		Table: `"order"."order"`,
		PK:    "id",
		Sort:  []string{"id", "date_created"},
		Fields: func(m *OrderOrder) map[string]any {
			return map[string]any{
				"id":                 &m.ID,
				"buyer_id":           &m.BuyerID,
				"seller_id":          &m.SellerID,
				"transport_id":       &m.TransportID,
				"address":            &m.Address,
				"date_created":       &m.DateCreated,
				"confirmed_by_id":    &m.ConfirmedByID,
				"confirm_session_id": &m.ConfirmSessionID,
				"note":               &m.Note,
			}
		},
	}
}

// OrderConds maps the filter params to predicates.
func OrderConds(f ListOrderParams) []repolist.Cond {
	return []repolist.Cond{
		repolist.In(`"id"`, f.Id),
		repolist.In(`"buyer_id"`, f.BuyerId),
		repolist.In(`"seller_id"`, f.SellerId),
		repolist.In(`"transport_id"`, f.TransportId),
		repolist.In(`"address"`, f.Address),
		repolist.In(`"date_created"`, f.DateCreated),
		repolist.Gte(`"date_created"`, f.DateCreatedFrom),
		repolist.Lte(`"date_created"`, f.DateCreatedTo),
		repolist.In(`"confirmed_by_id"`, f.ConfirmedById),
		repolist.In(`"confirm_session_id"`, f.ConfirmSessionId),
		repolist.In(`"note"`, f.Note),
	}
}

// ListOrder runs offset (?page) or cursor (?cursor/?sort) pagination over "order"."order".
func (q *Queries) ListOrder(ctx context.Context, f ListOrderParams) (paginate.PaginateResult[OrderOrder], error) {
	return repolist.List(ctx, q.db, f.Params, OrderQuery().Filter(OrderConds(f)...))
}
