// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package db

import (
	"context"
)

const existsCartItems = `-- name: ExistsCartItems :one
SELECT EXISTS(
    SELECT 1 FROM account.cart_item WHERE sku_id = ANY($1::bigint[])
) AS "exists"
`

func (q *Queries) ExistsCartItems(ctx context.Context, skuIds []int64) (bool, error) {
	row := q.db.QueryRow(ctx, existsCartItems, skuIds)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
